### ISSUE TITLE
nginx vhost configuration

### ISSUE THREAD

**Issue by equentor** [cretueusebiu/laravel-vue-spa#10]
What should be the virtual host configuration file?
I have an error after click to register or login button:

> POST http://localhost:8080/api/register 404 (Not Found)
dispatchXhrRequest @ xhr.js:177
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
createError.js:15 Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
createError @ createError.js:15
settle @ settle.js:18
handleLoad @ xhr.js:77

>Uncaught (in promise) Error: Request failed with status code 404
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
createError @ createError.js:15
settle @ settle.js:18
handleLoad @ xhr.js:77

**Comment by cretueusebiu** [comment]
It doesn't matter I use Laravel Valet and I have someting like `laravel-vue-spa.app`.
