### ISSUE TITLE
 php artisan migrate

### ISSUE THREAD

**Issue by MS-ELEX** [cretueusebiu/laravel-vue-spa#100]
when I tried command  "php artisan migrate",erros occurded.

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 458

  2   PDOStatement::execute()
      ....\vendor\laravel\framework\src\Illuminate\Database\Connection.php : 458

how can I resolve it??

**Comment by cretueusebiu** [comment]
See https://laravel-news.com/laravel-5-4-key-too-long-error
