### ISSUE TITLE
Start Loading before resolve page component

### ISSUE THREAD

**Issue by rodolfobubb** [cretueusebiu/laravel-vue-spa#104]
Hi,
it's possible to start the Loading bar before resolve page component (slow internet)?

Example:
With slow internet, when i click in 'Login', the application wait the download and has a delay before the loading starts:
`const Login = () => import('~/pages/auth/login')`
After this, start's the Loading to change the page.

But, i need to start the loading before resolve page component, it's possible?

**Comment by cretueusebiu** [comment]
You can access the loading bar component via `$root.$loading` where `$root` is the `App.vue` component.

```javascript
$root.$loading.start()
$root.$loading.finish()
```

Not sure where you use it, but take a look at [the router](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/router/index.js), you can find there how it's used.

I would suggest to try [laravel-nuxt](https://github.com/cretueusebiu/laravel-nuxt). It supports SSR and will always pre-fetch pages before you access them. 
I think it will help with slow internet connections.
