### ISSUE TITLE
Add Loading Animation Spinner

### ISSUE THREAD

**Issue by iamsrikanthgopi** [cretueusebiu/laravel-vue-spa#106]
I'm using this template for a single page application and everything worked fine. Before getting it to production i would like to add a loading animation so that users can know that the page is loading while switching between pages as the the page doesn't get refreshed.

I'm installed the below package using composer 
https://nguyenvanduocit.github.io/vue-loading-spinner/

I have added the below code in the layout file

```
<template>
  <div class="main-layout">
    <navbar/>
     <rotate-square2></rotate-square2>
    <div class="container mt-4">
      <child/>
    </div>
  </div>
</template>

<script>
import Navbar from '~/components/Navbar'
import {RotateSquare2} from 'vue-loading-spinner'
export default {
  name: 'MainLayout',
  components: {
    Navbar,
    RotateSquare2
  }
}
</script>
```

But the spinner doesn't show up. It works well with other templates but not with this spa template
I also see a Loading.vue in components.

Could you let me know if you have already added a loading animation that we could use in the project or any package that supports this template. I feel everyone who uses this template would like to add a loading spinner animation.

Thanks

**Comment by iamsrikanthgopi** [comment]
Here is the error snapshot [https://ibb.co/nxsvYJ](url)

**Comment by cretueusebiu** [comment]
You have to import the dist file, not the source.
