### ISSUE TITLE
Browser Freeze When Using SQL Server 2012 Database

### ISSUE THREAD

**Issue by yusren** [cretueusebiu/laravel-vue-spa#107]
Dear @cretueusebiu . When in development, I use MySQL database and all goes well. However I am facing problems if using MS SQL Server 2012 Database (production). My browser (Chrome, Edge and Firefox) freezes right after clicking the login button. Unlike the "too many redirect problems" that prompt browser errors, my browser tab is like freezing with waiting status at the bottom of the browser, tab loading spinner keep rotate counter clockwise (on Chrome) and the use of computer processors is increasing. I am confused whether this is VueJS / NodeJS problem or Laravel 5.6.
There is no error message on nodejs console CLI and also no php error log.
I'm using PHP SQL Server Extension version 4 for PHP 7.1.15
Thank you for your Attention

**Comment by cretueusebiu** [comment]
It's definitely Laravel related. Not sure what it could have to do with this project... 
Try with a fresh Laravel installation.

**Comment by yusren** [comment]
I've tried to downgrade to version 5.5 and the problem remains the same. You are right, this is related to Laravel. Because I tried to access every API url with GET method, all failed. I'm still trying to find the point of the problem. But why SQL Server?

**Comment by yusren** [comment]
I've tried to downgrade to version 5.5 and the problem remains the same. I'm still doubt if this is related to Laravel. Because I tried to access every API url with GET method, all success in new window browser. I'm still trying to find the point of the problem. But why SQL Server?
