### ISSUE TITLE
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages

### ISSUE THREAD

**Issue by ivanjj22** [cretueusebiu/laravel-vue-spa#109]
![captura](https://user-images.githubusercontent.com/9735440/41419736-5fde767a-6fb8-11e8-8643-2cc9a8d24a9c.PNG)

One CLI for webpack must be installed. These are recommended choices, delivered                      as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Which one do you like to install (webpack-cli/webpack-command):

**Comment by serkandyck** [comment]
You need install webpack-cli or webpack-command on your npm just npm install webpack-cli -g or npm install webpack-command -g or you can just add these package your package.json dev

**Comment by isometriq** [comment]
#122

**Comment by cretueusebiu** [comment]
Please just use `yarn` for now. If someone could submit a PR with a fix for `npm install` that would be great.

**Comment by Domiii** [comment]
Still suffering from the same issue; luckily I found a solution:

## Problem

Tried to build with `webpack` but `webpack-cli` was not installed, so it asked me:

> One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
>  - webpack-cli (https://github.com/webpack/webpack-cli)
>    The original webpack full-featured CLI.
> We will use "npm" to install the CLI via "npm install -D".
> Do you want to install 'webpack-cli' (yes/no): 

I said yes...

> Do you want to install 'webpack-cli' (yes/no): yes
> Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
up to date in

>  6.136s
> { Error: Cannot find module 'webpack-cli'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at runCommand.then (/Users/domi/code/dbdi/node_modules/webpack/bin/webpack.js:143:5)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1

Turns out that your internal attempt at installing fails:
1. `webpack-cli` did indeed get added to `package.json`'s `devDependencies`
1. But `$ npm list webpack-cli` shows:  `(empty)`

## Solution

Manually installing `webpack-cli` fixed it:

```sh
$ npm i -D webpack-cli
```

> \+ webpack-cli@3.2.3
> updated 1 package in 6.623s

**Comment by bvn13** [comment]
@Domiii does not help me. still receiving "do you want to install webpack-cli..."

**Comment by maoxiaoke** [comment]
@bvn13 
I tried the following steps: 

```bash
$ sudo su
# Input your passcode
```

Then 

```bash
npm install -g webpack webpack-cli
```
After that, you can run `webpack xxx` in root auth. May it help!

**Comment by GCinellu** [comment]
@maoxiaoke you should never install npm dependencies as `sudo`/`root`

**Comment by hrfahimi** [comment]
Just use it:
`sudo npm i -D webpack-cli -g`

**Comment by sumitvadhera01** [comment]
It did not work for me. Still showing the same error.

**Comment by arthabus** [comment]
worked for me after I've installed **locally** both `webpack` and `webpack-cli`. ie

```
npm i webpack webpack-cli -D
webpack
```

I had a global only webpack and a global + local webpack-cli before which gave me the same error as in the question.

**Comment by mudassir-sultan** [comment]
hi, i'm also face same issue.
**please try this: npm m install webpack -g**
hope it will help you

**Comment by Ali1** [comment]
I had some problems and as well as installing webpack-cli, I then went on to `npm install webpack -D` before it worked.
