### ISSUE TITLE
Feature Request: PWA

### ISSUE THREAD

**Issue by SaMiCoOo** [cretueusebiu/laravel-vue-spa#11]
Thank you for the awesome repo, I have been working hard to make this setup for 2 days now, dunno why the idea of searching for a ready setup did not come to mind. Really Thank you 😄 

I think adding PWA would make it more awesome, even if as an option.

**Comment by cretueusebiu** [comment]
You should check [Nuxt.js](https://github.com/nuxt/nuxt.js). It has support for PAW by default. I've used it with Laravel and works very well.
