### ISSUE TITLE
Bootstrap's JavaScript methods not working

### ISSUE THREAD

**Issue by matthiku** [cretueusebiu/laravel-vue-spa#113]
A bootstrap modal can be triggered via a data attribute or via JavaScript.

This works:
```
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Launch via data attribute
    </button>
    <div class="modal fade" id="exampleModal" ref="bsModal"
        tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
            <...>
      </div>
    </div>
```
This doesn't:
`this.$refs.bsModal.modal('toggle')`
It causes: "_this.$refs.bsModal.modal is not a function_"

I see that the bootstrap jQuery plugin is imported in `plugins\index.js` but is there anything else to do in order to enable those methods?

**Comment by cretueusebiu** [comment]
You have to wrap it with jQuery

`$(this.$refs.bsModal).modal('toggle')`

**Comment by matthiku** [comment]
I tried that as well and the result is: `Uncaught ReferenceError: $ is not defined`

**Comment by matthiku** [comment]
![image](https://user-images.githubusercontent.com/12457522/41787135-5de3e408-763f-11e8-9b62-c3894d129f18.png)

**Comment by cretueusebiu** [comment]
You have to import jQuery

`import $ from `jquery`

**Comment by matthiku** [comment]
Perfect, that's it! Thanks!!
