### ISSUE TITLE
Cannot resolve peer dependencies (Eslint & Webpack)

### ISSUE THREAD

**Issue by luebbert42** [cretueusebiu/laravel-vue-spa#114]
Question: from my understanding the current node modules require both eslint5 and 4 as peer dependencies. How do I resolve this? 

What I did

```
`composer` create-project --prefer-dist cretueusebiu/laravel-vue-spa
npm install
npm list

# eslint-config-standard wants version 5
npm ERR! peer dep missing: eslint@>=5.0.0-alpha.2, required by eslint-config-standard@12.0.0-alpha.0

# let's install it locally
npm install eslint@^5

# ok, but eslint-plugin-import wants eslint 2 or 4

npm WARN eslint-plugin-import@2.12.0 requires a peer of eslint@2.x - 4.x but none is installed. You must install peer dependencies yourself.

```

Some problem with webpack 4 and 3 which are required...

I understand that I can use npm-install-version to manually install a npm package in a version x into a subdirectory of node_modules, but the packages are not aware of my additional versions.

**Comment by cretueusebiu** [comment]
The projects comes with the yarn.lock file so just use `yarn` and ignore the warnings.

**Comment by luebbert42** [comment]
@cretueusebiu - had to downgrad to node 9 as upath in 1.04 requires a version < 10. After that it worked 4 me. With npm I got errors when running "npm run dev" that the templates are not valid. 
Thanks a lot for the help.
