### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by iamsrikanthgopi** [cretueusebiu/laravel-vue-spa#119]
I would like to use the blow font in the template
<link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet">

Im unable to find where the project main bootstrap css files are where i can change the font. I know i need to import it

**Comment by cretueusebiu** [comment]
You should use the Boostrap font variable `$font-family-sans-serif` and add it here [resources/assets/sass/_variables.scss](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/sass/_variables.scss).

**Comment by iamsrikanthgopi** [comment]
I have added <link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet"> to index view and $font-family: 'Megrim', cursive; to _variables.scss But still shows the old font

**Comment by iamsrikanthgopi** [comment]
Ok got it thanks
