### ISSUE TITLE
change layout 

### ISSUE THREAD

**Issue by davidoween** [cretueusebiu/laravel-vue-spa#12]
I want to change the layout for login, how can I do this?

**Comment by cretueusebiu** [comment]
Use the `layout` proprietary on the login component:

```javascript
export default {
  name: 'custom-layout'
}
```

Then create a new layout component in the [layouts](https://github.com/cretueusebiu/laravel-vue-spa/tree/master/resources/assets/js/layouts) directory.

**Comment by davidoween** [comment]
I have done that, and it does not work.

**Comment by davidoween** [comment]
It works now
