### ISSUE TITLE
Translation of Laravel validation messages

### ISSUE THREAD

**Issue by nfunwigabga** [cretueusebiu/laravel-vue-spa#120]
Hi,
Any way to localize validation (`422 response`) messages from laravel with the `vue-i18n` in this boilerplate?

Thanks

**Comment by cretueusebiu** [comment]
You have to define the Laravel translations for validation [here](https://github.com/cretueusebiu/laravel-vue-spa/tree/master/resources/lang). 
You can find the lines translated by [others](https://github.com/caouecs/Laravel-lang/).
