### ISSUE TITLE
Webpack 4  - Npm run dev error

### ISSUE THREAD

**Issue by yusufdemir** [cretueusebiu/laravel-vue-spa#122]
Npm run dev/watch or build process error 

**dep.getResourceIdentifier is not a function**

node -v v10.8.0
npm -v 6.2.0

**error details**
clone repo
npm i
npm i webpack-cli
npm run dev
This Error :

![image](https://user-images.githubusercontent.com/4970593/43666351-304a47cc-977c-11e8-9473-e15456131015.png)

**Comment by codisfy** [comment]
Just the same error I was having just a hour ago, came back here to see if this is already an issue and see your comment :) . 
https://github.com/webpack/webpack/issues/6675 talks about this. Seems like issue with Webpack 4 and Laravel Mix. I have spent more than an hour fixing errors after errors that were coming, including downgrading the webpack server@3.0.0, installing, node sass, sass loader, downgrading vue-loader@14.2 .  Now no errors but it takes forever to load to the app on local machine. 
Hope somebody out there has figured all of this out :)

**Comment by codisfy** [comment]
All worked well by using yarn instead of npm. There was an error with upath package but then removed it from yarn.lock and it worked. 
These 3 lines were removed. 
`upath@^1.0.0:
  version "1.0.4"
  resolved "https://registry.yarnpkg.com/upath/-/upath-1.0.4.tgz#ee2321ba0a786c50973db043a50b7bcba822361d"`

**Comment by isometriq** [comment]
So far i was able to work by
-removing lock files (yarn.lock & package-lock.json) and node_modules
-remove these packages from package.json:
    "@vue/cli-plugin-eslint": "^3.0.0-beta.9",
    "@vue/cli-service": "^3.0.0-beta.9",
    "@vue/eslint-config-standard": "^3.0.0-beta.9",
    "vue-template-compiler": "^2.5.16",
    "webpack-bundle-analyzer": "^2.11.2",
-npm install

Now npm run dev and watch works

However npm run prod builds but error appears in js console

app.js?id=700fb1942585307e8235:1 Uncaught ReferenceError: webpackJsonp is not defined
    at app.js?id=700fb1942585307e8235:1

**Comment by isometriq** [comment]
ok works in prod

thanks to this for pointing where to look
https://stackoverflow.com/questions/43304671/laravel-uncaught-referenceerror-webpackjsonp-is-not-defined-at-app-js1

in the .env, it must be set to production
APP_ENV=production
(because of condition in `resources/views/index.blade.php`)

**Comment by serkandyck** [comment]
Dont delete yarn.lock file if you windows and dont change any version on package.json and its working

**Comment by isometriq** [comment]
Yes initially that's what I did and it worked, but when I pushed on a repo and cloned on another machine, it did not work

**Comment by cretueusebiu** [comment]
Please just use `yarn` for now. If someone could submit a PR with a fix for `npm install` that would be great.
