### ISSUE TITLE
Hot Reload IP

### ISSUE THREAD

**Issue by sn0rcha** [cretueusebiu/laravel-vue-spa#129]
Hey Guys,

Thanks for the great boilerplate!

I have a quick question. I can't seem to get the hot reload working when working with a remote server. I have a local linux server 192.168.178.150 that is hosting the site. 

When running ```npm run watch``` it works no problem when accessing the site via the IP (on nginx).

When running ```npm run hot``` it tries to load the js and css from 'localhost:8080'. Is there anyway to change the IP for hot reload?

**Comment by cretueusebiu** [comment]
Try checking with [laravel-mix](https://github.com/JeffreyWay/laravel-mix).
