### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by iamsrikanthgopi** [cretueusebiu/laravel-vue-spa#130]
Does this support laravel 5.7 which comes with default email verification?

Laravel 5.7 features would make this starter app perfect for any use. Can't wait!

**Comment by ourfamilygithub** [comment]
Laravel 5.7 Please

**Comment by abhi-cognitivo** [comment]
5.7 would be great, but I think we can do it on our own. How easy do you guys think it would be to upgrade to 5.7??

**Comment by cretueusebiu** [comment]
You can find the upgrade guide to 5.7 [here](https://laravel.com/docs/5.7/upgrade#upgrade-5.7.0).
