### ISSUE TITLE
How to use middleware on routes

### ISSUE THREAD

**Issue by molerat619** [cretueusebiu/laravel-vue-spa#136]
Hey @cretueusebiu,

can you show a simple example on how to use the auth middleware on vue js routes? Is it possible to use it on a parent route so all children are also protected?

Thank you!

**Comment by qWici** [comment]
@molerat619 just add middleware to your parent component. 
Example:
```js
File - router/router.js
...
{ path: '/settings',
    component: Settings,
    children: [
      { path: '', redirect: { name: 'settings.profile' } },
      { path: 'profile', name: 'settings.profile', component: SettingsProfile },
      { path: 'password', name: 'settings.password', component: SettingsPassword }
    ] },
...
```
```js
File - settings/index (parent component)

export default {
  middleware: 'auth',
}
```

**Comment by molerat619** [comment]
That would explain, why I couldn't find any middleware logic in the routes-file :) Thank you!

**Comment by qWici** [comment]
@molerat619 np
@cretueusebiu close
