### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by davidoween** [cretueusebiu/laravel-vue-spa#14]
Refresh token to expire in 1 hour. Only expire when the user does not interact with the page

thanks

**Comment by cretueusebiu** [comment]
I use [jwt-auth](https://github.com/tymondesigns/jwt-auth) for JWT tokens.

To increase the lifetime set `JWT_TTL` in your `.env` file. 

For example 1 day (in minutes):
```
JWT_TTL=1440
```

**Comment by davidoween** [comment]
And to refresh constantly when the user navigates the page? And close when I do not navigate the page?

**Comment by cretueusebiu** [comment]
Not sure it's possible.

**Comment by sgasser** [comment]
Token should be refreshed with refresh token: https://laracasts.com/discuss/channels/general-discussion/auto-refresh-a-jwt-token/replies/183104

**Comment by Insua** [comment]
@cretueusebiu ingore refresh token is realy safe? you make me  confused

**Comment by cretueusebiu** [comment]
I use this package for [jwt](https://github.com/tymondesigns/jwt-auth) authentication and it has a refresh token mechanism. 
So you could implement it, but for this template I'll keep it simple with just an access token. 

If you want to go even further I'd suggest [Laravel Passport](https://laravel.com/docs/5.5/passport).
