### ISSUE TITLE
Unable to prepare route [{path}] for serialization. Uses Closure

### ISSUE THREAD

**Issue by mpjraaij** [cretueusebiu/laravel-vue-spa#141]
Hi there,

When I run `php artisan route:cache` I get `Unable to prepare route [{path}] for serialization. Uses Closure.`

How can I solve this?

**Comment by cretueusebiu** [comment]
There are some routes that don't use a controller and can't be serialized. Just add a controller and move the code there.

https://github.com/cretueusebiu/laravel-vue-spa/tree/master/routes
