### ISSUE TITLE
Understanding the code

### ISSUE THREAD

**Issue by amirakbulut** [cretueusebiu/laravel-vue-spa#144]
Is there a way for me to understand your resources\js folder structure?
Are you planning on documenting it?

**Comment by cretueusebiu** [comment]
This is something similar to [Nuxt](https://nuxtjs.org/). 
But I also have a [laravel-nuxt](https://github.com/cretueusebiu/laravel-nuxt) template, so you could just use that an refer to the [Nuxt documentation](https://nuxtjs.org/guide) for the structure and how it works.
