### ISSUE TITLE
how can i add more plugins

### ISSUE THREAD

**Issue by musman92** [cretueusebiu/laravel-vue-spa#145]
i need to add more plugins, how can i?

i need to add this plugin
https://www.npmjs.com/package/vue-toasted

**Comment by luisalcarasr** [comment]
1. Install the package: `npm install vue-toasted --save`
2. Import it and add it.
```
import Toasted from 'vue-toasted';
Vue.use(Toasted)
```
3. Use it.

**Comment by cretueusebiu** [comment]
Just create another file in `resources/js/plugins` and then include it in `resources/js/plugins/index.js`
