### ISSUE TITLE
how i can add mixins 

### ISSUE THREAD

**Issue by musman92** [cretueusebiu/laravel-vue-spa#148]
i want to create mixins 
https://vuejs.org/v2/guide/mixins.html
how i can add them, i try creating a folder, "mixins" and create a mixin "ExamleMixin"
when i import it into component i got error. 

import ExamleMixin from '../../mixins/ExamleMixin'

it give me error
Module not found: Error: Can't resolve  '../../mixins/ExamleMixin'

i check with path and stuff its fine. 
can anyone give me a example 
thanks in adv

**Comment by cretueusebiu** [comment]
Use:

`import ExamleMixin from '~/mixins/ExamleMixin'`

**Comment by musman92** [comment]
@cretueusebiu buddy i try this, but 

i found this
To install it, you can run: npm install --save ~/mixins/ExamleMixin
