### ISSUE TITLE
Fetch as Google blank page

### ISSUE THREAD

**Issue by Hukuta** [cretueusebiu/laravel-vue-spa#153]
Fetch as Google renders site as blank page:
![Image](https://cdn-images-1.medium.com/max/2000/1*mYhZfF1WnoFNXPFUnnjk1w.png)

checked on errors with [this](https://blog.codaxy.com/debugging-googlebot-crawl-errors-for-javascript-applications-5d9134c06ee7) method, no any errors - a blank page.

Any solution how to fix or debug this?

**Comment by Hukuta** [comment]
[pull request to fix this](https://github.com/cretueusebiu/laravel-vue-spa/pull/155)

**Comment by h-zone** [comment]
@Hukuta - LIKE! 👍

**Comment by cretueusebiu** [comment]
Fetch as Google has been replaced with URL Inspection tool and it seems to work.  https://support.google.com/webmasters/answer/9073702?hl=en

For IE for example you can use `babel-polyfill` https://github.com/JeffreyWay/laravel-mix/issues/436#issuecomment-281374759
