### ISSUE TITLE
How to know current route name or path in vue compoment?

### ISSUE THREAD

**Issue by JHanAlex** [cretueusebiu/laravel-vue-spa#157]
Please help, I study to learn vue and I don't understand how I can know what route is opening now.
I use menu items and I want to mark menu active if value of menu items equal to route name.
As I understand from code all routes are sync in store. How in component I can get current opened route.

**Comment by cretueusebiu** [comment]
See https://router.vuejs.org

this.$route in methods and $route in component template.
