### ISSUE TITLE
Just wondering...

### ISSUE THREAD

**Issue by jinseokoh** [cretueusebiu/laravel-vue-spa#16]
I found your scripts a great material to learn the basics of how to scaffold SPA with VueJS. While I followed your code to see how and why things are laid out that way, I can't get the reason behind this:

https://github.com/cretueusebiu/laravel-vue-spa/blob/d342a09e6546a90027470ea0e78f2330d4e6c56d/resources/assets/js/components/App.vue#L37-L39

To me it doesn't seem it's necessary. Can you please tell me why you wrote the line? Thank you so much, and keep up the great work.

**Comment by cretueusebiu** [comment]
🤔 Not sure either. Should be removed.
