### ISSUE TITLE
Quick question regarding js files generated during development (under npm run watch)

### ISSUE THREAD

**Issue by manu144x** [cretueusebiu/laravel-vue-spa#160]
This not really an issue, just trying to understand better what's happening in JS as I'm more of a PHP/Laravel guy. 

So I understand that during the development, you are generating those files using hashes, so that you bypass any potential browser caching, 

Is there a way to clean them up automatically when preparing for production, or you just add them to .gitignore, or delete them manually, or how exactly should it be done?

Personally on another laravel projects, I'm using the defaults, which doesn't have hashing not even for production, I'm just using a random number in the Laravel layout to bypass the cache, and even without that, in Chrome, if you have the console open it will skip the cache anyway.

I am asking because each time I work I get a ton of files generated during development, while on another projects I only get one clean file, which when I run for production is simply replaced with the production version of that same file.

Thank you, and great job so far, I think something like this should be a standard. I'm using it for like 3-4 small experimental projects, and I'm moving so fast I love it.

**Comment by cretueusebiu** [comment]
This project uses [dynamic imports](https://webpack.js.org/guides/code-splitting/), so for each page will generate a js file with only the code for that page. This is used to reduce the main js bundle so the initial load is faster.

If you want to disable dynamic imports you'll have to remove/change some code:

From `webpack.mix.js` remove:

```js
if (mix.inProduction()) {
   ....
}

...

output: {
  chunkFilename: 'js/[name].[chunkhash].js',
  publicPath: mix.config.hmr ? '//localhost:8080' : '/'
}
```

In `resources/js/router/routes.js` replace every:

```js
const Component = () => import('~/pages/component').then(m => m.default || m)
```

with:

```js
import Component from '~/pages/component'
```

Replace `resources/js/plugins/i18n.js` with:

```js
import Vue from 'vue'
import store from '~/store'
import VueI18n from 'vue-i18n'
import en from '~/lang/en'

Vue.use(VueI18n)

const i18n = new VueI18n({
  locale: 'en',
  messages: {
    en: en
  }
})

export function loadMessages (locale) {
  if (i18n.locale !== locale) {
    i18n.locale = locale
  }
}

export default i18n
```

From `resources/views/index.blade.php` remove:

```php
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
```

Now you'll only have a `app.js` file.

**Comment by manu144x** [comment]
No, i think I didn't explain myself correctly.

I understand that it's using dynamic loading, which I like for faster loading. I was just wondering if there's an automated way to clean them up when getting ready to generate for production, or I can just delete manually all the hashed ones generated while developing.


For example when you are ready to push to production, what should do you normally do, technically just do a npm run production and then commit them, right? Because now my generated files look like in the picture, and what I do is I delete all of them, run npm run production which generates me the latest file ready to commit. But all the other older versions are still left there.

![image](https://user-images.githubusercontent.com/6595887/52432306-cec60380-2b12-11e9-9bee-6a163dcb5228.png)

**Comment by manu144x** [comment]
@cretueusebiu As far as I found, this is could be a webmix bug, they say the newer version does this, while the older one doesn't. 

During "run watch", it seems that each file update, generates a new file, with a new hash, instead of the old one.  I am running it under Windows, could that be the issue?

For now I think I will install a cleanup package and have it run before production to clean up everything.
