### ISSUE TITLE
Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in

### ISSUE THREAD

**Issue by carlosgbp00027** [cretueusebiu/laravel-vue-spa#161]
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"

file: "D:\xampp\htdocs\repuestos\vendor\lcobucci\jwt\src\Signer\Hmac.php"

line: 29

message: "Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in D:\xampp\htdocs\repuestos\vendor\lcobucci\jwt\src\Signer\BaseSigner.php on line 42"

don't work 
php artisan config:cache
php artisan cache:config
php artisan jwt:generate
php artisan jwt:secret

**Comment by Evoolo** [comment]
I have the same issue on a local windows environment with Laragon.

On my Ubuntu server everything works.

**Comment by carlosgbp00027** [comment]
muchas gracias, ha funcionado esa configuracion.
