### ISSUE TITLE
Localization issue + email verification page

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#167]
Hi, @cretueusebiu !
Again im about localization :(

Frontend localization dont know what happens at backend. And reverse, backend dont know about frontend.

If backend stores strictly localized content, we need to send request, when switching locale, to the backend to change locale at the backend. And we need to receive response of successful switching.

In essence, this does not happen.

**It is not enough to switch the interface language, it is necessary to tell the backend about this.**

And still no intercept page for email verification. Why?

I very glad that You not abandone this package.
Thank You for Your work!

**Comment by h-zone** [comment]
In addition, i think, better solution is work with Laravel's localization files (resources/lang/{locale}) and populate theese files into json.
Look for my solution (not ideal, but works)
https://gist.github.com/h-zone/d93fb05fe12047dd25c70907c7c555cf

**Comment by cretueusebiu** [comment]
You can make an api call when the locale changes in [lang.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/store/modules/lang.js#L26) and set the locale on the server too.

The default email verification from Laravel doesn't really work by default with the stateless auth guard. 
So for this we need something custom. I'll see what I can pull from my other projects. 

Right now I'm waiting for [laravel-mix](https://github.com/JeffreyWay/laravel-mix) to be fixed so I can tag another release.

**Comment by h-zone** [comment]
> 
> 
> You can make an api call when the locale changes in [lang.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/store/modules/lang.js#L26) and set the locale on the server too.
> 
> The default email verification from Laravel doesn't really work by default with the stateless auth guard.
> So for this we need something custom. I'll see what I can pull from my other projects.
> 
> Right now I'm waiting for [laravel-mix](https://github.com/JeffreyWay/laravel-mix) to be fixed so I can tag another release.

no, i cant.
your new release will overwrites my changes.

may i join your team?:)

**Comment by cretueusebiu** [comment]
I've added email verification to the master branch. 
After few more tests I'll probably release a new version.
