### ISSUE TITLE
How to deploy on digitalocean

### ISSUE THREAD

**Issue by Malieh** [cretueusebiu/laravel-vue-spa#169]
Thank you for the laravel-vue-spa template. it has been very helpful to me. I developed a project using this template and now I have dificulties deploying the application. I have been deploying laravel sites for long but i have never deployed a laravel vue spa website.
I am using nginx as webserver on digital ocean. I will be very happy if you can help

**Comment by TemaSM** [comment]
Hi @Malieh
First of all you need to install PHP >= 7.1, and configure it to be used by Nginx (php-fastcgi, php-fpm,...).
Next, install Node.js into your droplet, I recommend using [NVM](https://github.com/nvm-sh/nvm#installation-and-update). Simple command to install nodejs after installing NVM:
`nvm install 'lts/*'` - it will install current active LTS (v10.15.3).
Third step - follow [install instructions](https://github.com/cretueusebiu/laravel-vue-spa#installation) from `laravel-vue-spa` readme, excluding first item.
And as final, run in terminal from root of your website `npm run prod` - it will build all needed JS/CSS, so your frontend will be ready for production use.
Profit! Website with Laravel on backend and Vue.js on frontend successfully  deployed onto your droplet at DigialOcean.
