### ISSUE TITLE
browserSync not reloading page

### ISSUE THREAD

**Issue by ilgala** [cretueusebiu/laravel-vue-spa#177]
Hi everyone. I've use this repository as "boilerplate" for another project and I'd like to know how to configure browserSync.

For me i's the first time that I approach to the frontend world with a "more detailed eye" and I'd like to know a little deeper the tools I'm using.

ATM I've changed the `webpack.mix.js` as follows:

```
if (mix.inProduction()) {
  mix
    // .extract() // Disabled until resolved: https://github.com/JeffreyWay/laravel-mix/issues/1889
    // .version() // Use `laravel-mix-versionhash` for the generating correct Laravel Mix manifest file.
    .versionHash()
} else {
  mix.sourceMaps()
  .browserSync({
      proxy: 'mydomain.test'                        // <-- Here my code
  })
}
```

It starts... But when I do any kind of update, the page doesn't reload.
Thanks in advance

**Comment by jettaz** [comment]
>   .browserSync({
>       proxy: 'mydomain.test'                        // <-- Here my code
>   })

dont know if you still need answer, but here is my solution:
just add this code to browserSync

`  files: [
    'app/**/*',
    'public/**/*',
    'resources/**/*',
  ],`
