### ISSUE TITLE
can't compile images to public directory

### ISSUE THREAD

**Issue by jettaz** [cretueusebiu/laravel-vue-spa#179]
oke i have started to use this repository on 19-05-2019
i have used 2 days to get images to my project and i just dont get it.
have cheked all issues in this repository and chaked issues on webpack.mix repository 

i have installed this repository like it says in read me.
have used composer to install it. 
used all npms and still didnt got it 
dont have any error's in console or in npm 

i will show it 

**Like you see on webpage left top, you will see logo is missing and we missing here a background image**
![website](https://user-images.githubusercontent.com/36550461/58041646-dc8b1c00-7b38-11e9-9f05-abd5444802cc.png)

**on network you will see it try to load** 
![network](https://user-images.githubusercontent.com/36550461/58041754-312e9700-7b39-11e9-978f-d49d2903a24c.png)

**you will see its compiling in npm**
![npm](https://user-images.githubusercontent.com/36550461/58041816-591dfa80-7b39-11e9-8940-b05f9ddf6dce.png)

**but it still missing in public directory**
![map](https://user-images.githubusercontent.com/36550461/58041858-74890580-7b39-11e9-8a78-e739bd4050f5.png)

i just dont get it, what i am missing ??

**Comment by cretueusebiu** [comment]
You have to put your images in the public directory.

**Comment by jettaz** [comment]
> You have to put your images in the public directory.

thx for you fast answer

but i am searching for something else. 
if i am using standard laravel + vue + standard webpack-mix, basic laravel settings.
![webpack-mix](https://user-images.githubusercontent.com/36550461/58049976-65608280-7b4e-11e9-8610-833cce8cafc3.png)

it will compile all images what i am using in resources directory
![npm](https://user-images.githubusercontent.com/36550461/58050039-8b862280-7b4e-11e9-868e-f7d7e75fed99.png)

automatic to my public directory with same path like i coded in my files 
![directorys](https://user-images.githubusercontent.com/36550461/58050211-02232000-7b4f-11e9-83ff-a403f082b2d6.png)

do i need to add some thing to your webpack.mix.js ?? 
[https://github.com/cretueusebiu/laravel-vue-spa/blob/master/webpack.mix.js](url)

in my previous post you see that your webpack configurations compiling the image, but that image disappears after compiling.

so i need that it does the same job like in standard laravel webpack.mix.js

**Comment by cretueusebiu** [comment]
There is an issue with `.extract()` when using dynamic imports in Mix 4.
 That might be the cause for images too.

https://github.com/JeffreyWay/laravel-mix/issues/1889

**Comment by jettaz** [comment]
thx for answer, 
i will keep an eye on laravel-mix 
=)
