### ISSUE TITLE
how to change env

### ISSUE THREAD

**Issue by musman92** [cretueusebiu/laravel-vue-spa#180]
you use in view 
`@if (app()->isLocal())
    <script src="{{ mix('js/app.js') }}"></script>
  @else
    <script src="{{ mix('js/manifest.js') }}"></script>
    <script src="{{ mix('js/vendor.js') }}"></script>
    <script src="{{ mix('js/app.js') }}"></script>
  @endif`
how you change the env local to production, i update in .env file but it did not work.
also i run "npm run prod"

**Comment by cretueusebiu** [comment]
You probably have the config cached.

Run `php artisan config:clear`
