### ISSUE TITLE
TypeError: popper is null

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#181]
trying to use bootstrap's dropdown.
getting an eroor: `TypeError: popper is null`
adding popper.js in any position (already have some sexual experience) has no effect.
mix.autoload - no effect
in code pre-requiring/importing - no effect.

lost day

**Comment by h-zone** [comment]
also sourceMaps not works too.
helps only:
```
mix.webpackConfig({devtool: 'source-map'})
     .sourceMaps()
```

**Comment by dimer22zhc** [comment]
why people don't respond here
