### ISSUE TITLE
why you refuse to answer

### ISSUE THREAD

**Issue by dimer22zhc** [cretueusebiu/laravel-vue-spa#185]
import axios from 'axios'
import * as types from '../mutation-types'

// post
export const state = {
  post: []
}

// getters
export const getters = {
  post: state => state.post
}

// mutations
export const mutations = {
  [types.FETCH_POST_SUCCESS] (state, { post }) {
    state.post = post
  },
  [types.FETCH_POST_FAILURE] (state) {
    state.post = null
  }
}

// actions
export const actions = {
  // auth/fetchPost
  async post ({ commit }) {
    try {
      const { data } = await axios.get('/api/post')
      commit(types.FETCH_POST_SUCCESS, { post: data })
    } catch (e) {
      commit(types.FETCH_POST_FAILURE)
    }
  }
}

**Comment by iamazik** [comment]
What's your issue here?
