### ISSUE TITLE
error npm run dev don't exist folder public/fonts

### ISSUE THREAD

**Issue by carlos00027** [cretueusebiu/laravel-vue-spa#188]
I think the project with Compositor but I execute "npm run dev" but I do not get the "public / fonts" folder to do there? I've been cloning this repository for months because it's the best I've seen but now it's useless. Can anybody help me?

**Comment by cretueusebiu** [comment]
There is no fonts directory. This uses fontawesome 5 with svg fronts.

**Comment by carlos00027** [comment]
in the function publishAseets add 

`fs.copySync(path.join(publicDir, 'build', 'fonts'), path.join(publicDir, 'fonts'))` 


after a while of researching and testing. The addition of the mentioned line and it has worked. I use a frame called element and this is its own source and since the source folder does not exist in the production directory, the styles generated errors.

I do not speak English, I use a translator. thousand excuses

**Comment by h-zone** [comment]
i think, @cretueusebiu , need to re-build an frontend app with new vue-cli under new phpStorm (2019.2+).

yesterday i have been surprised...

building of app is faster, no need tons of accompanying packages.

simple understanding as general thing

**Comment by h-zone** [comment]
> 
> 
> There is no fonts directory. This uses fontawesome 5 with svg fronts.

bad way, because of some people uses pro or not a svg version. your variant is forced developer to use an svg version.
so, cutting out fonts and dependencies can harm the psyche of the programmer :)

**Comment by h-zone** [comment]
works only version 1.0.8
1.0.7 in package.json of this project
