### ISSUE TITLE
Always Loading Open Sans Font

### ISSUE THREAD

**Issue by bmpf** [cretueusebiu/laravel-vue-spa#190]
How can I remove the Open Sans from loading ? 
![image](https://user-images.githubusercontent.com/33966960/61522398-33628400-aa0a-11e9-984e-f502f393ae47.png)

I already search the whole package for : 'Open Sans', 'OpenSans', 'Sans' and i didn't find anything relevant to this issue.

**Comment by cretueusebiu** [comment]
It's not included in the template view-source:https://laravel-vue-spa.cretueusebiu.com

**Comment by bmpf** [comment]
Sorry it was some extension in my browser.
![image](https://user-images.githubusercontent.com/33966960/61546131-d59d5e80-aa40-11e9-8520-55176a1201eb.png)
