### ISSUE TITLE
Append Language locale to the URL [Locale-Adaptive Web Pages]

### ISSUE THREAD

**Issue by bmpf** [cretueusebiu/laravel-vue-spa#191]
Its there a way to append the locale to the url base.

For Example : 
127.0.0.1/**en**/settings/profile
127.0.0.1/**es**/settings/profile
127.0.0.1/**cn**/settings/profile

Motive: Crawling & Indexing Locale-Adaptive Web Pages

**Comment by cretueusebiu** [comment]
I think you have to add something like `/:locale?/login` and then using a [global middleware](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/router/index.js#L12) check that and set it in store.
