### ISSUE TITLE
Login with Github not working

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/laravel-vue-spa#193]
I went through the steps in the Readme for Github authentication but it does not work. This is also unrelated to a prior issue reported in #182.

**Steps followed after installation:**
Add new Github application from https://github.com/settings/applications/xxxxxxxxxx
Github application settings used (example):
```
Client ID: d708f83e843805880423
Client Secret: 2222f9ae68123223e0d1548a27eaa5a4e37695433
Homepage URL: http://localhost:8000
Authorization callback URL: http://localhost:8000
```
Note that in Github's app settings, the Authorization callback URL is a REQUIRED field.

**.env file settings**: (example, changed for privacy)
```
GITHUB_CLIENT_ID=d708f83e843805880423
GITHUB_CLIENT_SECRET=2222f9ae68123223e0d1548a27eaa5a4e37695433
```
It matches the Github app settings.

Now open the app and go to http://127.0.0.1:8000/register
Click 'Login with Github' button. A new window opens and you're taken to this URL:
screenshot: https://1ce.org/1#rkdbOcjMH

http://localhost:8000/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

I looked at the github documentation:
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls
where it says:
```
The redirect_uri parameter is optional. If left out, GitHub will redirect users to the callback URL configured in the OAuth Application settings. If provided, the redirect URL's host and port must exactly match the callback URL.
```

**The OAuthController.php file** contains:
```
    public function __construct()
    {
        config([
            'services.github.redirect' => route('oauth.callback', 'github'),
        ]);
    }
```
But a 'redirect' config key does not exist in config/services.php:
```
    'github' => [
        'client_id' => env('GITHUB_CLIENT_ID'),
        'client_secret' => env('GITHUB_CLIENT_SECRET'),
    ],
```
I also tried adding it (and making it match the Authorization callback URL, but it did not help).

What am I missing? What and where should the Authorization callback URL be set? Is this the same as "The redirect_uri parameter" mentioned on the Github help page?

**Comment by cretueusebiu** [comment]
You can see the error in the url:
`error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application`

You have to set the redirect url on your GitHub app to `https://example.com/api/oauth/github/callback`

**Comment by connecteev** [comment]
I'll submit a PR to fix the documentation once I figure this out, but still something is missing.

My Github settings: https://1ce.org/1#SJy7V92fS
My env file matches the Github settings

When I click on "Login with GIthub": https://1ce.org/1#Hk1kN9nfS

Error: http://localhost:8000/api/oauth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

```
"""
Client error: `GET https://api.github.com/user?access_token=` resulted in a `401 Unauthorized` response:
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/users/#get-the-authent (truncated...)
"""

```

Are you seeing this at all?

**Comment by cretueusebiu** [comment]
I'm not sure what you're doing wrong... But it works in my demo https://laravel-vue-spa.cretueusebiu.com/login

**Comment by connecteev** [comment]
Yes, I saw that...it works fine on your demo link!
For what it's worth, I did get github working on this repo: https://github.com/jeremykenedy/laravel-auth
But this codebase you are working on is a lot cleaner, and I'd love to try to get it to work here. Just not sure why I am seeing a 401 unauthorized despite following all the instructions.

**Comment by stfarm** [comment]
Does 127.0.0.1 work or will I need a real domain name to get this to work? I have the same issue right now.
