### ISSUE TITLE
Auth Session Expiration

### ISSUE THREAD

**Issue by unickortega** [cretueusebiu/laravel-vue-spa#195]
How do we set Session Expiration.
I think it would nice to be able to set the expiration date or time for the token because the session all of a sudden expires even though I enable `Remember me` on the login page.

Thank you by the way!
I've used  this project starter template for a number of my projects and I find it very useful and it lets me focus building functionality rather than having to set it up from the scratch.

**Comment by cretueusebiu** [comment]
Set JWT_TTL in .env to the number of seconds you want your token to be.

**Comment by unickortega** [comment]
I see. Thank you!
