### ISSUE TITLE
How to re enable csrf ?

### ISSUE THREAD

**Issue by bmpf** [cretueusebiu/laravel-vue-spa#198]
How can i re enable csrf ? 

I already uncommented the lines in the App\Http\Kernel but I still can make post requests with postman without the csrf field in the header.

**Comment by bmpf** [comment]
I think this ll solve it maybe :/ ?

'api' => [
            'throttle:60,1',
            'bindings',
            \Illuminate\Session\Middleware\StartSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
        ],

**Comment by cretueusebiu** [comment]
You don't have to use a csrf token with this template because it uses a token when making a request to the server.

**Comment by bmpf** [comment]
I have a couple of forms that you dont need to be logged in order to send them. I can 'abuse' them via script or postman with constant fake posts requests. 
All I put in the headers are the Accept Key. And nothing else. 
![image](https://user-images.githubusercontent.com/33966960/64760178-f1991a00-d530-11e9-8c9f-767158f6adc5.png)

**Comment by bmpf** [comment]
is there a guest Bearer  ?

**Comment by cretueusebiu** [comment]
I think you can enable back all the middleware. 
I've disabled them because it as it is now you don't need them.
But if you have some other pages where you need csrf token, you can enable all of them back.
