### ISSUE TITLE
Hmmm, - an issue :)

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#2]
Hi!
I like your job!
But.

- how to fast fix localhost:8080 error, if im behind NAT and TWO proxying web-servers ?

it is possible to use FQDN on port 80 ? And how  (im stuck).

**Comment by cretueusebiu** [comment]
Where exactly do you get this error ?

**Comment by h-zone** [comment]
basicly, in `index.blade.php` we have lines
```
  @if (!ScriptVariables::hotReload())
    <link rel="stylesheet" href="{{ elixir('css/app.css') }}">
  @endif
```
and
```
  @if (ScriptVariables::hotReload())
    <script src="https://re-linked.net/app.js"></script>
  @else
```
Of course page is blank. No errors in laravel, but of course console says blocked http from https://localhost....
a) http can not be requested from https protocol page
b) im using real domain name, (not localhost)

How can i see changes if my server is virual machine behind proxying web-server (nginx) behind NAT and uses ONLY httpS protocol ?

This is really one bug-feature, preventing to install your package to development farms.

**Comment by h-zone** [comment]
additionaly:
changing hosts and ports in `/build/`-files - has no effects. Page still blank.

im new in HMR and bad understand this mechanic

**Comment by h-zone** [comment]
and last - please make an documentation, what files resposive for what feature/logic. it is helps your package to be popular

**Comment by cretueusebiu** [comment]
HMR only works with http. This is still a work in progress project so there's not too much info on it.

**Comment by h-zone** [comment]
Okay, may be worth to add a new dev-command to build js/css (not compressed and/or for debugging) without listening servers ?
Can you do that ?

Another request(s):
- add translation variables to the DOM to use in templates (ScriptVariables.php)
- add config with list of config variables/group of variables for adding to the DOM, and read it while pushing data in ScriptVariables.php... I have poor English, I know ((

**Comment by cretueusebiu** [comment]
It only supports HMR or build. if you want just a watch, check out [laravel-mix](https://github.com/JeffreyWay/laravel-mix).

Translation are on the TODO list.

You can push variables using `ScriptVariables::add($key, $value)` and will be available in the `window.config` variable.

**Comment by cretueusebiu** [comment]
If you download the latest version, it uses [laravel-mix](https://github.com/JeffreyWay/laravel-mix) by default. So you can run: `npm run watch` and will compile and watch for changes without hot reload.
