### ISSUE TITLE
Navigation between long pages issue

### ISSUE THREAD

**Issue by this-user-name** [cretueusebiu/laravel-vue-spa#201]
When navigating between pages within the same layout (Or not) there is a behavior that is not very much user friendly in my view. 

For example if is there a **route-link** in the middle/bottom of the page upon click the page goes to top very fast and then is showed the new page. Its kind of annoying :/ 

Is there any way to fix this ?

Example: 
![image](https://user-images.githubusercontent.com/55763682/65543755-be2f9580-df09-11e9-93c8-8231caabec33.png)

**Comment by bmpf** [comment]
There is a quick fix: 

Remove `return { x: 0, y: 0 }` and replace it with a **Promise Async Scrolling** , set it to 190 (+-) 
Read more @ [https://router.vuejs.org/guide/advanced/scroll-behavior.html](https://router.vuejs.org/guide/advanced/scroll-behavior.html)

```
function scrollBehavior (to, from, savedPosition) {
  if (savedPosition) {
    return savedPosition
  }

  if (to.hash) {
    return { selector: to.hash }
  }

  const [component] = router.getMatchedComponents({ ...to }).slice(-1)

  if (component && component.scrollToTop === false) {
    return {}
  }

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({ x: 0, y: 0 })
    }, 190)
  })

  //return { x: 0, y: 0 }
}
```

**Comment by this-user-name** [comment]
It worked . thanks

**Comment by jimohalloran** [comment]
Seems like a pretty low risk change to make everywhere.  @cretueusebiu would you like a PR to add this into this project?

**Comment by cretueusebiu** [comment]
Yeah sure, but what default value should we use ? 100 / 150 / 200 ?

**Comment by bmpf** [comment]
I have found the sweet spot to be **190** ms, I use the same ms in multiple apps , but , just to be safe , you can set it to **200** , You cant notice any difference whatsoever. 
You can also play around with css transitions in other to make the value lower. In my view there is no point , the user ll never notice any diference, and a little feedback ( clean and soft page transition) is always nice.

**Comment by jimohalloran** [comment]
Cool, I had thought a nice CSS scroll back to the top instead of a snap might be nice.  I'll try a few different things starting at 190/200 and see what seems to look best.

**Comment by cretueusebiu** [comment]
@jimohalloran Sounds great!

I've seen your other PRs and will hopefully review and merge them very soon.

**Comment by jimohalloran** [comment]
No rush, whenever you get time.  I've got a bit of spare time at the moment, so just giving a little back to a project that's given me a lot over the last year.  If there's anything you specifically want me to take a look at, sing out.  Happy to help where I can.
