### ISSUE TITLE
Route links for the same 'layout' is not moving to top (scroll)

### ISSUE THREAD

**Issue by nelson6e65** [cretueusebiu/laravel-vue-spa#21]
This is your `scrollBehaviour` of `router`: 

```js
function scrollBehavior (to, from, savedPosition) {
  if (savedPosition) {
    return savedPosition
  }

  const position = {}

  if (to.hash) {
    position.selector = to.hash
  }

  if (to.matched.some(m => m.meta.scrollToTop)) {
    position.x = 0
    position.y = 0
  }

  return position
}
```

I'm having 2 issues:

:one: If I move from page A to page B, using the same layout (app), the scroll keeps in same position when I click links. This is noticeable in large pages.

If I use a different layout for B, then it works as expected. **How can I move to top for navigation?** The `savedPosition` should be for Browser back, doesn't?

:two: Links to hash do not works neither (I mean, scroll to a section). Again, only works if I use different layourts. 

Making simple inspects, `if (to.hash)` enters, but is not applied if we are in the same layout. 

> Also, browser back/forward do not scrolls to the hash.

The layouts implementation of this boilerplate is great! :tada:  But I'm running into this issues (I'm not expert in Vue). :disappointed:

**Comment by cretueusebiu** [comment]
You can just change the [scrollBehavior](https://router.vuejs.org/en/advanced/scroll-behavior.html) on the Vue Router how you wish.

You can maybe add another prop in your component that tells you if it should scroll to top or not, then in `scrollBehavior` you can have something like `const [component] = router.getMatchedComponents({ ...to })`  to get the first matching component and see if that prop exists and scroll.

**Comment by nelson6e65** [comment]
> You can maybe add another prop in your component that tells you if it should scroll to top or not.
Then in scrollBehavior you can have something like const [component] = router.getMatchedComponents({ ...to }) to get the first matching component and see if that prop exists and scroll.

Yes, maybe I could add something like that for an specific component. But... I want _all_ sub-views move to top, and move to hash, like I think is defined in the bundled `scrollBehavior` in your package.

It's fine. It works if I use different layouts. I'm just saying that it do not works for views using the same `layout`.

I'll add some examples about this and link here.

**Comment by nelson6e65** [comment]
```js
function scrollBehavior (to, from, savedPosition) {
  return { x: 0, y: 0 }
}
```

Even if I use this, it do not works.

**Comment by nelson6e65** [comment]
I had to apply this work-around, because I use other than `<body>` for my main scroll:

```html
<div id="app">
  <div class="layout-x">
    <nav id="my fixed navbar" />
    <div class="content" /> <!-- Here is my main scroll -->
  </div>
</div>
```

```js
  /**
   * Workarrownd para mover al top al cambiar de ruta.
   *
   * TODO: Buscar una forma de implementar como scrollBehavior más bien.
   *
   * @type {[type]}
   */
  router.afterEach((to, from) => {
    const mainScrollContainer = document.getElementById('content')

    if (mainScrollContainer != null && !to.hash) {
      setTimeout(() => {
        mainScrollContainer.scrollTo(0, 0)
      }, 400)
    }
  })
```

**Comment by cretueusebiu** [comment]
Now it will always scroll to top unless `scrollToTop: false` is set in component or a hash exists.
