### ISSUE TITLE
 I wonder if it is possible to include the Pt-Br language?

### ISSUE THREAD

**Issue by lecastro** [cretueusebiu/laravel-vue-spa#210]
I really enjoyed the project and found it cool to do a translation for pt-br.

**Comment by sleepycodernotes** [comment]
Why not? )

**Comment by sleepycodernotes** [comment]
Add lang in app conf, and make dir for lang with exactly same folders as others

**Comment by connecteev** [comment]
@lecastro @sleepycodernotes check out https://github.com/cretueusebiu/laravel-nuxt
Nuxt has all the benefits of this package, but it also does server-side rendering (for SEO) out of the box.

**Comment by bmpf** [comment]
@connecteev google can crawl spa. That's not a big issue anymore.

**Comment by vahidalvandi** [comment]
> @connecteev google can crawl spa. That's not a big issue anymore.

Are you sure؟؟؟

**Comment by bmpf** [comment]
> > @connecteev google can crawl spa. That's not a big issue anymore.
> 
> Are you sure؟؟؟

Yes, i have several websites with spa and google crawls them. 

If you use this app, google only crawl the default website language. If you want all languages you have to do something like website.com/en/some-link || website.com/es/some-link etc...

**Comment by bmpf** [comment]
Also, you can do some middleware in laravel to render out pages for bing and other search engines that cant run javascript. 
`if ( header = 'bingbot' ) { return view(page/for/bing }
`

**Comment by vahidalvandi** [comment]
> Also, you can do some middleware in laravel to render out pages for bing and other search engines that cant run javascript.
> `if ( header = 'bingbot' ) { return view(page/for/bing } `

i will build a website with multi language , laravel have package https://github.com/mcamara/laravel-localization it add locale code in all routes , but how i can in this project ... please Description  it

**Comment by bmpf** [comment]
This project already comes with translation. but not with the links. /en /es /fr etc....
