### ISSUE TITLE
Using Vuetify

### ISSUE THREAD

**Issue by talentedaamer** [cretueusebiu/laravel-vue-spa#211]
How Vuetify can be used properly.? importing in app.js and using with Vue.use() does not work.

**Comment by bmpf** [comment]
Yes : 

Install vuetify,

Create File : /plugins/vuetify.js

```
import Vue from 'vue'
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify)

const opts = {}

export default new Vuetify(opts)
```

Add to  /plugins/index.js
```
import './vuetify'
```

**Comment by talentedaamer** [comment]
Thank you I figured it out with in the following way.

File resources/js/app.js

```
import Vuetify from 'vuetify';
import 'vuetify/dist/vuetify.min.css'
Vue.use(Vuetify);
```

Then Initialize the plugin with some options

```
new Vue({
  i18n,
  store,
  router,
  ...App,
  vuetify: new Vuetify({
    icons: {
      iconfont: 'mdi',
    },
  })
})
```

**Comment by jettaz** [comment]
@talentedaamer @bmpf 
@talentedaamer, did you have problem with colors ?
i did the same thing, my vue components are working.
but i have problem with default color's, i just dont get the default colors work, like: primary secondery, success etc. 

here is my github repo https://github.com/jettaz/av-vuetifyjs 

can some one check what i am doing wrong ?

**Comment by jettaz** [comment]
Found solution in vuetify discord.
Vue-meta is way outdated and npm update didnt help.
So uninstall vue-meta and install it again and evry thing will works fine !

**Comment by uppergoal** [comment]
I personally prefer to use the Nuxt modules when available so I don't have to import any plugin and can import the module and set configurations directly from the nuxt.config.js file. 
Nuxt module explained: https://nuxtjs.org/guide/modules/
Vuetify module: https://github.com/nuxt-community/vuetify-module

**Comment by h-zone** [comment]
its hard to implement vuetify.
layouts, pages, themes and styles...
a lot of work for doubtful buns.

and if we need rapidly change vuetify to another one framework?
a lot of work again?

**Comment by h-zone** [comment]
so, i think we need ui switcher with pre-defined frameworks.
also i think its must be entirely app and resources directories.

**Comment by vahidalvandi** [comment]
hi to all

how i can use this pre-made vuetify in this app ?

https://vuetifyjs.com/en/examples/layouts/complex/

**Comment by JayCasee** [comment]
Just for someone who may have same problems which I've faced...

1.
After following the above, the CSS of Vuetify makes some conflicts with Laravel Mix CSS.
So, you need to remove it in `resouces/views/spa.blade.php`.
```
{{--<link rel="stylesheet" href="{{ mix('dist/css/app.css') }}">--}}
```

2.
Also the above has no mentioning about Material Design Icons.
This link may gives many different solutions.
https://stackoverflow.com/questions/57053728/vuetify-icon-not-showing
In my case, S Verma's answer was the solution.

3.
Regarding the above vahidalvandi's question...
[1] Make a Vue page file in `resource/js/page`.
[2] Copy and paste the example code on the Vue page file.
[3] Add the Vue page file route on `resources/js/router/routes.js`

**Comment by Rubens10010** [comment]
> Found solution in vuetify discord.
> Vue-meta is way outdated and npm update didnt help.
> So uninstall vue-meta and install it again and evry thing will works fine !

Thank you so much that was the final solution for me I tried almost everything else (didn't work).
