### ISSUE TITLE
vendor folder not download by composer install?

### ISSUE THREAD

**Issue by samreachyan** [cretueusebiu/laravel-vue-spa#215]
when I clone your project into my directory. I cannot use composer install to get vendor folder. My composer not error but not support your vue-spa. I dont know why. I can use composer to download laravel ( it's also download vendor folder normally) except laravel-vue-spa. npm install (working normally). 

vendor folder in composer not download, I cannot migrate DB. cannot start project. Do you have any recommendations.? Thanks​ you in advance

**Comment by bmpf** [comment]
**Instalation :** composer create-project --prefer-dist cretueusebiu/laravel-vue-spa
