### ISSUE TITLE
Why some api calls directly in components and other in store?

### ISSUE THREAD

**Issue by nicolagaldiolo** [cretueusebiu/laravel-vue-spa#217]
Hi, i notice that you make some Api call in components directly (all call maked with form object) and all other Api call (via axios) you've maked in store actions. 
Which pattern is better to follow?
Can you explain the correct way to manage Api call?

Thanks so much.

**Comment by cretueusebiu** [comment]
When I use the [form object](https://github.com/cretueusebiu/vform) or it's a request for some data just for the component I leave it in the component. 
When you need to fetch/create/update/delete something and it does affect the state in multiple places I would use the store.

**Comment by xazinji** [comment]
I generally use this flowchart approach. 

![](https://markus.oberlehner.net/images/2018-05-27/should-i-store-this-data-in-vuex-flow-chart.png)
