### ISSUE TITLE
What is the difference between laravel-vue-spa and laravel-nuxt of cretueusebiu?

### ISSUE THREAD

**Issue by jettaz** [cretueusebiu/laravel-vue-spa#224]
Hallo,
I am searching for good bassis for my future project. 
There is a big hype about nuxt and i have ready read alot of things about spa and nuxt on google, but still confusing. 

1. what is difference between this repository(laravel-vue-spa) and laravel-nuxt from cretuesebie ? 
2. what are the benefits to use this repository or nuxt example ? 
3. is this one for small projects or can it be used for big project too ?
4. is nuxt example made for big projects ?

can any one help me ?

**Comment by idhowardgj94** [comment]
i didn't have much experience about vue or nuxt.
but I have some experience about react, and also use vue in a project.

as my opinion, 
nuxt is just a vue tool that help u bundle all ur vue code,
and u can avoid to configuring hell before you start write ur vue code.

but actually, laravel's official version integrate vue, and offer a bundle tool name 'laravel-mix' which base on webpack but you can a lot more easier, and avoid some annoying configuration. so, even you don't use nuxt, you can easily setup a vue project.

so I think, which you want to choose, it's depends on ur work. if u inherit other's project, and it use nuxt, maybe you can choose laravel-nuxt to start your project. if not, i'm not a big fan to customize framework's project structure, so maybe i'll choose laravel-vue.

and for the .3rd and 4th q. How big ur project really is?

I think if ur prjoect really big, you may need to split ur app into some smaller sub-app. but it's not about u using vue or flux. as my opinion, you certainly can use this two template in big project. it's matter on how u design ur code.

**Comment by jettaz** [comment]
@idhowardgj94 thx for your answer =)
