### ISSUE TITLE
problemas con package-lock.json y npm run watch

### ISSUE THREAD

**Issue by carlos00027** [cretueusebiu/laravel-vue-spa#227]
si se elimina "node_modules" y "package-lock.json" y posteriormente ejecutar "npm i " el "npm run watch" no vuelve a funcionar el "browserSync" creeria que el archivo "package.json" de este repositorio presenta algún problema. podrías revisarlo por favor.

**Comment by jimohalloran** [comment]
I've checked out the master branch of this repo, deleted `node_modules` as suggested, then reinstalled dependencies with `npm i` and had no issues running `npm run watch`.  I'm not accustomed to "watch" doing any kind of browser sync or hot module reloading (I use it all the time).  Maybe `npm run hot` is that you're looking for?

**Comment by jimohalloran** [comment]
For completeness, my `npm version` output:
```{ npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.1',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }```

**Comment by carlos00027** [comment]
Regards, I found the problem. They had already mentioned it before in the mistakes of this project. In the "webpack.js" file it is necessary to require the "laravel-mix-versionhas" packet only when compiled for production. I have taken this from the official documentation of the NPM package

if (mix.inProduction()) {
  require('laravel-mix-versionhash')
  mix.versionHash()
}


https://www.npmjs.com/package/laravel-mix-versionhash


I remind you that this problem happens after removing the "node_modules" and also the "package-lock.json" I use "browserync" from "laravelmix"
