### ISSUE TITLE
window.opener is null at firefox and ie. opera - fine

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#235]
@cretueusebiu please respond asap.

Authentication works only with local project.
Any social authentication which uses popup will not works.
Possible problems:
- browser nullify the `window opener` when redirect occurs
- need to use cors

**Comment by h-zone** [comment]
may be use HelloJS / Vue-Authentication ?

**Comment by h-zone** [comment]
in addition:
in firefox if toggle and back any security option like as cookie - all works

**Comment by PHPGuus** [comment]
@h-zone What do you mean with "toggle and back any security option" specifically, please? I see in Firefox using facebook login, that the `window.opener` exists before I go to facebook, but the moment I come back from facebook `window.opener` is null.. So I'm wondering how this did work for you, please ;-)
