### ISSUE TITLE
Javascript error in prod env

### ISSUE THREAD

**Issue by sgasser** [cretueusebiu/laravel-vue-spa#24]
Hi,

after 

```npm run prod```

I get following javascript error on a clean installation:
```Uncaught ReferenceError: webpackJsonp is not defined```

**Comment by cretueusebiu** [comment]
For production you'll have to set the `APP_ENV=production` in your `.env` file.

**Comment by sgasser** [comment]
I tried again but no luck...

This are the steps for the installation:

- git clone git@github.com:cretueusebiu/laravel-vue-spa.git
- cd laravel-vue-spa/
- cp .env.example .env
- update APP_ENV=production
- composer install --no-dev
- php artisan key:generate
- php artisan jwt:secret
- Edit .env and set your database connection details
- php artisan migrate
- yarn
- npm run production
- php artisan serve

But I get always this error:
![selection_048](https://user-images.githubusercontent.com/850416/31315787-b5e36fd8-ac1f-11e7-865f-d532ac6ebe44.png)

**Comment by cretueusebiu** [comment]
What do you get if you `dd(app()->environment());` ?

**Comment by sgasser** [comment]
Where should I write ``dd(app()->environment());``

``php artisan env`` returns
``Current application environment: production``

``npm run production`` returns no error.

I get the error ``Uncaught ReferenceError: webpackJsonp is not defined`` when I open http://127.0.0.1:8000

**Comment by cretueusebiu** [comment]
Try using a domain for your app with Valet or Homestead.

**Comment by wa05** [comment]
Same problem here http://inmobiliariaforti.com/administracion_alquileres/public/ ...
