### ISSUE TITLE
A question regarding upgrading to the latest version.

### ISSUE THREAD

**Issue by manu144x** [cretueusebiu/laravel-vue-spa#241]
Let's say I built a small project using this project, but it was a long version ago.

What would be the recommended strategy to upgrade to the latest version? 
Just do a merge with the latest version of this project maybe? 

Or checkout the latest version, and move back all the added code (models, controllers, views, etc)?

I wanted to upgrade anyway to Laravel 7 and since this is already done and tested, might as well do it this way.

Thank you for any tips.

**Comment by cretueusebiu** [comment]
You would just follow the Laravel upgrade guide from version to version (... 5.8 to 6.x, 6.x to 7.x ...)
https://laravel.com/docs/7.x/upgrade

You don't need to upgrade the client since that didn't change that much.
