### ISSUE TITLE
Installing with yarn makes webpack build to the wrong location

### ISSUE THREAD

**Issue by augustpemberton** [cretueusebiu/laravel-vue-spa#243]
When following the [install instructions](https://github.com/cretueusebiu/laravel-vue-spa), if you use `yarn` instead of `npm`, the webpack files will build to `public/build/dist` rather than `public/dist`.

This in turn breaks the build, as all the <script> tags point to the wrong location.

I'm not sure why this is, maybe yarn is installing the wrong version of webpack? I'd prefer to use yarn over npm so if anyone has any advice about this it would be greatly appreciated.
Thanks!

**EDIT:** it seems like yarn works fine after initially installing with npm.

**Comment by augustpemberton** [comment]
can be fixed by editing `webpack.config.js`:
https://github.com/cretueusebiu/laravel-vue-spa/issues/230#issuecomment-614530923

**Comment by cretueusebiu** [comment]
Because there's no yarn.lock, Yarn will probably install the wrong version of the deps.
