### ISSUE TITLE
Cannot cache routes

### ISSUE THREAD

**Issue by Firtzberg** [cretueusebiu/laravel-vue-spa#245]
A proper laravel application should enable route caching when put into production.
This is not supported when closures are used.
You should extract returning of the index view into a controller to make the process possible.

**Comment by miraries** [comment]
Creating a project through the laravel installer does this as well, luckily it's easy to move the `api/user` route to a controller (eg. ProfileController), and the one in `web.php` to
```php
Route::view('{path}', 'index')->where('path', '^(?!api).*$');
```

I'd make a PR but it seems only laravel upgrade-related ones are being merged.

**Comment by Firtzberg** [comment]
Duplicate of https://github.com/cretueusebiu/laravel-vue-spa/issues/141
Seems like multiple users of this project deal with the same thing. I think this should be solved here for all of them.
@cretueusebiu Let me know if you are willing to accept a PR on this.

**Comment by cretueusebiu** [comment]
@Firtzberg Sure! Thanks.
