### ISSUE TITLE
Vuetify

### ISSUE THREAD

**Issue by cmihaiandrei1995** [cretueusebiu/laravel-vue-spa#246]
Hello,

When I try to install Vuetify and Vuetify loader it keeps on telling me the vuetify is undefined. I installed everything correctly, at least I think so. I modified the webpack to use the vuetify-loader.
What am I missing?

**Comment by Greenvold** [comment]
Hi,

I am using Vuetify on this project and it is working. 

I made vuetify plugin file:


```
import Vue from "vue";
import Vuetify from "vuetify/lib";

Vue.use(Vuetify);

export default new Vuetify({});

```
```
new Vue({
  vuetify,
  router,
  store,
  ...App,
}).$mount("#app");
```

Don't forget to import vuetify from plugins in main.js.


and this is a part of my main.js file:
