### ISSUE TITLE
Move index route to new route group

### ISSUE THREAD

**Issue by Firtzberg** [cretueusebiu/laravel-vue-spa#247]
The index route in the [routes/web.php](https://github.com/cretueusebiu/laravel-vue-spa/blob/4.6.0/routes/web.php) is misplaced and [web middleware group](https://github.com/cretueusebiu/laravel-vue-spa/blob/4.6.0/app/Http/Kernel.php#L35) not appropriate for web requests. The web routes and middleware are meant for session related requests as you can read in the [app/Providers/RouteServiceProvider.php](https://github.com/cretueusebiu/laravel-vue-spa/blob/4.6.0/app/Providers/RouteServiceProvider.php#L48).

This in general is no big deal until you start integrating 3rd party packages like [laravel-roles](https://github.com/jeremykenedy/laravel-roles) which use the 'web' middleware internally for their builtin admin panel.

I used that package in my project and realized the proper way to do this is to restore the 'web' middleware group and create a new one for my SPA index only. I added a new mapping to the RouteServiceProvider as below and moved the spa index endpoint to a new routes file.

```php
    /**
     * Define the "spa" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapSpaRoutes()
    {
        Route::middleware('spa')
             ->namespace($this->namespace)
             ->group(base_path('routes/spa.php'));
    }
```

This allows me to have the API routes, SPA application and MVC based administration panel working side-by-side.

**Comment by Firtzberg** [comment]
Let me know if you're interested in a PR.
Possibly related
- https://github.com/cretueusebiu/laravel-vue-spa/issues/198
- https://github.com/cretueusebiu/laravel-vue-spa/issues/90
- https://github.com/cretueusebiu/laravel-vue-spa/issues/9

**Comment by cretueusebiu** [comment]
If you could create a PR that would be great!
