### ISSUE TITLE
cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

### ISSUE THREAD

**Issue by mostadev** [cretueusebiu/laravel-vue-spa#25]
after migrating database then installed yarn the i've run this command 
npm run production

`> @ production E:\wamp64\www\mostadev\crud\1
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1`

**Comment by cretueusebiu** [comment]
Make sure `cross-env` is installed. Run `yarn` inside the project to install the npm dependencies.
