### ISSUE TITLE
Authentication in webview blocked

### ISSUE THREAD

**Issue by clemjlt** [cretueusebiu/laravel-vue-spa#250]
I've found a problem when using the authentication in 2 situations :
- When the SPA is added to homescreen
- When the SPA is used in a the android webview

The opened window, where the authentication is supposed to happen, is blocked as you can see in the below video, and it's impossible to continue the login/register flow.

![SVID_20200410_091828_1_Trim](https://user-images.githubusercontent.com/10855219/78972773-d74b0d00-7b0e-11ea-8da2-0de182fb0e4c.gif)

Maybe related to #94 and #235 ?

**Comment by h-zone** [comment]
check for `winfow.opener` is not null
if is null:
- social auth partially not works, because most browser for now nullify winfow.opener after redirect to callback url
- if this problem with local auth, check modifications in Kernal.php / js files and try again with clean project from github
