### ISSUE TITLE
use code spitting for improve performance and decrease app.js file size

### ISSUE THREAD

**Issue by vahidalvandi** [cretueusebiu/laravel-vue-spa#252]
please see this tutotial and use it in code spilitting , because one of bad things in spa in large app.js in big projects

https://sebastiandedeyne.com/posts/2018/code-splitting-with-laravel-mix

you can split group of component in one app , EX : home , setting in two app.js

**Comment by cretueusebiu** [comment]
Code splitting is already used for pages in [resources/js/router/routes.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/router/routes.js).

**Comment by vahidalvandi** [comment]
very thanks
