### ISSUE TITLE
Unnecessary method call

### ISSUE THREAD

**Issue by nandi95** [cretueusebiu/laravel-vue-spa#253]
In the `RegisterController.php` @ line:45 the method `$user->sendEmailVerificationNotification();` should not be called given that in the `RegisterUsers` trait the register method already fires the event `Registered` which in turn fires the `SendEmailVerificationNotification` as per it set in the `EventServiceProvider` in the `$listen` array.

Either remove the event listener in the event service provider or the method call in the `registered` method`.

I think it's easier to follow if the lister is removed and the method explicitly called.

I'm happy to make a PR when decided which one to remove.

**Comment by cretueusebiu** [comment]
A PR would be great!
