### ISSUE TITLE
Spa routes?

### ISSUE THREAD

**Issue by ezequiel9** [cretueusebiu/laravel-vue-spa#259]
Before, thanks for doing this.. it's a very nice setup for spa. 

I don't really get what is the Spa routes for? I mean, there si already web.php to declare routes, what is the purpose for that?

Thanks

**Comment by cretueusebiu** [comment]
The SPA routes are used just for the one route that includes the spa view. The routing is done in JS by Vue Router.

Before it was used the web middleware and routes and if you had another thing that you wanted to plug into your Laravel app instalation that was depended on the web middleware you would have ran into some issues.
