### ISSUE TITLE
Issue running this project in a place different than "/"

### ISSUE THREAD

**Issue by icaroscherma** [cretueusebiu/laravel-vue-spa#26]
If I try to run this project in an apache envinronment with multiple other projects without Vhost to a root folder with different domain (ex.: `http://dev.local/scherma/laravel-vue-spa/public/`), it fails...

Is there a way to Laravel Mix to point straight to the right folder, like `{{ asset('css/app.css') }}` instead of `mix` , and also I did run `npm run production` and even so I get the error of `webpackjsonp` is not defined (missing `manifest``  and `vendor`, maybe) ...

The solution found was to manually edit the `assets/views/` `index.blade.php` and `scripts.blade.php` to add the base-url. But even so the VueRouter gets buggy, trying to route to the `/login` instead of `base-url/login` :P

**Comment by cretueusebiu** [comment]
Keep the changes in the blade file and then add the [base](https://router.vuejs.org/en/api/options.html#base) option to the Vue router [here](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/router/index.js#L26). 
If that still doesn't work you will need a dedicated domain.
