### ISSUE TITLE
update jwt to laravel sanctum 

### ISSUE THREAD

**Issue by vahidalvandi** [cretueusebiu/laravel-vue-spa#260]
update jwt to laravel sanctum  also you can remove       `  "tymon/jwt-auth": "^1.0.0" ` and remove         `"fruitcake/laravel-cors": "^1.0",`  instance you official  way in laravel 7

**Comment by vahidalvandi** [comment]
https://serversideup.net/using-laravel-sanctum-airlock-with-nuxtjs/

**Comment by Snakzi** [comment]
any news on this?

**Comment by cretueusebiu** [comment]
I've published a new branch for Laravel Sanctum if you want to test it.
Now I'm wondering if I should merge it in master or not... 🤔

**Comment by h-zone** [comment]
> I've published a new branch for Laravel Sanctum if you want to test it.
> Now I'm wondering if I should merge it in master or not... 🤔

just create a new project then transfer all required packages.
i see, that this project need a fresh build with pre-render optional implementation, like Your nuxt version.

**Comment by h-zone** [comment]
Also I think it would be great to implement Fortify to use **two-factor authentication**. Convenient, right?

**Comment by h-zone** [comment]
And lastly, I think it's right to switch to taiulwindcss and provide for the possibility of using a variety of color schemes, which, it seems to me, will increase both the audience and the number of problems :) you yourself understand that it's boring without problems :)

**Comment by cretueusebiu** [comment]
Moving to #325
