### ISSUE TITLE
How best way to create another middleware 

### ISSUE THREAD

**Issue by Adhik13th** [cretueusebiu/laravel-vue-spa#262]
Hello , iam sorry , iam new and first studying about SPA , in there i found admin.js

```
`import store from '~/store'

export default (to, from, next) => {
  if (store.getters['auth/user'].role !== 'admin') {
    next({ name: 'home' })
  } else {
    next()
  }
}
`
```

i dont know where this role == admin from where , and how i can add more this like , admin , superadmin,users etc ? can someone tell me how to best way to create this middleware ?

**Comment by rushadaev** [comment]
store.getters['auth/user'] just fetched object of authorized users. And here you just check if this user has some role in this object fetched from database. So what you need is make sure that you have this information in your db.
For example I made another column in my db, just role_id  and use store.getters['auth/user'] .role_id != 1, for admin, for example. So like this middleware you can just create your own middleware with your own rule just duplicate this file, give him new name and change rule thats how I do.

**Comment by Adhik13th** [comment]
ok so i need create another colomn in my users tables like role_id , but on this code on my script its have 

` if (store.getters['auth/user'].role !== 'admin') {
    next({ name: 'home' })`

so this line is not used on script if we dont have colomn 'role' ???

**Comment by bmpf** [comment]
Yes you have to create something that says that user is admin (database), and then set it in the modules/auth.js when fetched. 
That middleware/admin.js is just an example, its not used in the application. There is no _role_ in the database.
