### ISSUE TITLE
The npm run watch is ignored, it always loads the production version

### ISSUE THREAD

**Issue by manu144x** [cretueusebiu/laravel-vue-spa#264]
I tried everything, the .env is set correctly, I am dumping the app.env into the main html just to be sure:

![image](https://user-images.githubusercontent.com/6595887/81489171-58ff9900-927b-11ea-8078-20b5025db6a9.png)

however it still tries to load only the production version. 

If i run npm run production, it works perfectly fine.

However with npm run watch active, (all is working fine with it, it detects the changes, recompiles), except in Chrome (both incognito and clearing the cache) still loads the last production version built.

Am I missing something, did I mis-configure anything? 

I'm running on Windows 10 with WAMP if that may be an issue, and this is my package.json:

`{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "npm run development -- --watch",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "lint": "eslint --fix --ext .js,.vue resources/js"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-regular-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/vue-fontawesome": "^0.1.9",
    "axios": "^0.18.1",
    "bootstrap": "^4.4.1",
    "jquery": "^3.5.1",
    "js-cookie": "^2.2.1",
    "moment": "^2.22.2",
    "moment-duration-format": "^2.2.2",
    "popper.js": "^1.16.1-lts",
    "sweetalert2": "^8.19.0",
    "vform": "^1.0.1",
    "vue": "^2.6.11",
    "vue-i18n": "^8.17.4",
    "vue-meta": "^1.6.0",
    "vue-multiselect": "^2.1.3",
    "vue-router": "^3.1.6",
    "vuex": "^3.3.0",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.9.6",
    "babel-eslint": "^10.1.0",
    "bootstrap-vue": "^2.13.1",
    "cross-env": "^5.2.1",
    "eslint": "^5.16.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^9.2.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^5.2.3",
    "laravel-mix": "^4.1.4",
    "laravel-mix-versionhash": "^1.1.3",
    "resolve-url-loader": "^2.3.1",
    "sass": "^1.26.5",
    "sass-loader": "^7.3.1",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^3.7.0"
  }
}
`

I can't figure out why it's doing this.

I noticed in the previous versions you were doing an "if" in the blade template, and load the correct js based on the .env, is that something that I would have to do?

**Comment by manu144x** [comment]
I was able to replicate the issue.

I checked out the project again, and it worked fine.
I assumed it was something about my stuff, so as I began putting everything back (models, controller, vue files, etc) I kept testing.

It all worked fine.

After I did npm run update, it stopped working. It only loads the production version and that's it. 
npm run watch and npm run hot work perfectly fine, but they're ignored in the browser, and the npm hot is just loading forever.

Some updated version of some package kills it for some reason. 

So I deleted the npm modules, the package-lock.json file too, and ran a fresh npm install, but still doesn't work.

It always looks for the production version. If I have it, it uses it, if I delete the dist and run npm run watch directly, it says not found and won't load the "npm run watch" at all.

I can't figure out why.

**Comment by manu144x** [comment]
So I managed to get it working again, by restoring the package-lock.json from the previous commit (the very first installation) and doing an npm install. 

I know this time it restored it because it warns me about 1000 vulnerabilities.

So something is messing it up in the updated packages.

**Comment by TPGT00019** [comment]
Me too, I changed code but it always loads product version. What i have missing ?

**Comment by manu144x** [comment]
Don't do npm update, something is breaking it.

**Comment by TPGT00019** [comment]
@manu144x  thanks for answers. Using "npm run  production" command is working.

**Comment by manu144x** [comment]
Actually the same issue as this one:
https://github.com/cretueusebiu/laravel-vue-spa/issues/230
