### ISSUE TITLE
Laravel mix doesn't create dist folder

### ISSUE THREAD

**Issue by falahatiali** [cretueusebiu/laravel-vue-spa#265]
sometimes when I add a new library and npm run watch also is executing it doesn't compile new files and don't create new dist folder in public

**Comment by AndrewMast** [comment]
I have the same issue. It appears that the `publishAssets()` function doesn't run. I fixed it by changing the output path from `'./public/build'` to `'./public'` (and commented out lines 38-53). Don't know if that will mess anything up in the future though.

**Comment by falahatiali** [comment]
@AndrewMast 
I have found out a new thing but I don't know why. look at line 39 and 43. 
for the first time that you want run npm run watch dont comment anything but after the first time comment lines 39 and 43
```
// mix.then(() => {
if (!mix.config.hmr) {
    process.nextTick(() => publishAseets())
  }
// });
```

it runs and rebuild dist folder. but for me my new changes are not affected.
