### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by emanuelriolan** [cretueusebiu/laravel-vue-spa#269]
Everything is work, unfortunly error show on console :

xhr.js?b50d:160 PATCH http://localhost:8002/api/settings/password 422 (Unprocessable Entity)
vue.common.dev.js?4650:630 [Vue warn]: Error in v-on handler (Promise/async): "Error: Request failed with status code 422"
found in

---> <Password> at resources/js/pages/settings/password.vue
       <Index> at resources/js/pages/settings/index.vue
         <Child> at resources/js/components/Child.vue
           <MainLayout> at resources/js/layouts/default.vue
             <Root>
vue.common.dev.js?4650:1893 Error: Request failed with status code 422
    at createError (createError.js?2d83:16)
    at settle (settle.js?467f:18)
    at XMLHttpRequest.handleLoad (xhr.js?b50d:59)

**Comment by bmpf** [comment]
Error 422 Unprocessable Entity : means the request was invalid. 
Maybe you were logged out or the token was expired when making the request. (Wrong username or password)
