### ISSUE TITLE
[suggestion] Publish to Composer in order to be able to `create-project`

### ISSUE THREAD

**Issue by nelson6e65** [cretueusebiu/laravel-vue-spa#27]
Update your composer `name` and publish to https://packagist.org/ in order to be able to create a base project as Laravel installation, like:

```bash
composer create-project --prefer-dist cretueusebiu/laravel-vue-spa my-app
```

**Comment by cretueusebiu** [comment]
The project has been published to Packagist.
https://packagist.org/packages/cretueusebiu/laravel-vue-spa
