### ISSUE TITLE
Duplicate Verify Email Address

### ISSUE THREAD

**Issue by altynbek07** [cretueusebiu/laravel-vue-spa#270]
I enabled `Illuminate\Contracts\Auth\MustVerifyEmail` in `App\User`. Then I registered and received two identical "Verify Email Address" mails. Attached a screenshot.
![image](https://user-images.githubusercontent.com/20629188/85152622-aa357c00-b26e-11ea-8503-cb551333d7bb.png)

---
I commented this line and received only one mail:
```php
protected function registered(Request $request, User $user)
    {
        if ($user instanceof MustVerifyEmail) {
            // $user->sendEmailVerificationNotification();

            return response()->json(['status' => trans('verification.sent')]);
        }

        return response()->json($user);
    }
```

**Comment by Markoftw** [comment]
Are you on the recent version? Seems like it was already removed with commit https://github.com/cretueusebiu/laravel-vue-spa/commit/85b8be2e83cd6b1a9d8d6b946eccd3f8e0db6c40

**Comment by altynbek07** [comment]
@Markoftw Thank you. But it looks like the new version has not yet been released?
