### ISSUE TITLE
How to use js and css in production?

### ISSUE THREAD

**Issue by bhavinjr** [cretueusebiu/laravel-vue-spa#277]
The Code and architecture is really very good.
Now question is how to use
`dist/css/app.css` and `dist/js/app.js` in production mode/live server where `dist` directory is in `.gitignore` file

How to handle these files?

**Comment by bmpf** [comment]
`>npm run production `

views/index.blade.php reads the mix-manifest.json that has the full path. 

```
<link rel="stylesheet" href="{{ mix('dist/css/app.css') }}">
<script src="{{ mix('dist/js/app.js') }}"></script>
```
