### ISSUE TITLE
How to use multi auth in this project.

### ISSUE THREAD

**Issue by newtest12-dev** [cretueusebiu/laravel-vue-spa#278]
Would you please suggest me how to make admin and user panel separately in this project.

**Comment by IngusGraholskis** [comment]
I would also love to see this!

**Comment by h-zone** [comment]
store auth[] ?

**Comment by IngusGraholskis** [comment]
> store auth[] ?

I m new to laravel could you tell me more?

**Comment by h-zone** [comment]
> 
> 
> > store auth[] ?
> 
> I m new to laravel could you tell me more?

this is not laravel speciefic.
and nope. learn arrays
