### ISSUE TITLE
Defualt Vuex Action?

### ISSUE THREAD

**Issue by jbonnett92** [cretueusebiu/laravel-vue-spa#28]
Hi,
Is there a default vuex action? I noticed that in store/modules/auth you have fetchUser although I can't find where that is getting called, so my assumption is that there is a dynamic action call?

update:
I added the following code
```
try {
  await store.dispatch('fetchDefault')
} catch (e) {}
```
to the router like so:
```
  // Register before guard.
  router.beforeEach(async(to, from, next) => {
    if (!store.getters.authCheck && store.getters.authToken) {
      try {
        await store.dispatch('fetchUser')
      } catch (e) {}
    }

    try {
      await store.dispatch('fetchDefault')
    } catch (e) {}

    setLayout(router, to)
    next()
  })
```
Please let me know if there is a better way of approaching this problem.

Any help would be much appreciated.
Jamie

**Comment by cretueusebiu** [comment]
The `fetchUser` action is dispatched in `login.vue` and `router/index.js`.
