### ISSUE TITLE
Uncaught (in promise) Error: Cannot find module './app()->getLocale()'  at eval (eval at ./resources/js/lang lazy recursive ^\.\/.*$ (app.js:1603)

### ISSUE THREAD

**Issue by passkok** [cretueusebiu/laravel-vue-spa#283]
Hi
I get this error when load my page

 Uncaught (in promise) Error: Cannot find module './app()->getLocale()'  at eval (eval at ./resources/js/lang lazy recursive ^\.\/.*$ (app.js:1603)

Can help me please.

**Comment by bmpf** [comment]
You have and non-existent language set in cookies.
