### ISSUE TITLE
laravel 8, vue 3 version has come ?

### ISSUE THREAD

**Issue by furkangurel** [cretueusebiu/laravel-vue-spa#285]

**Comment by Elzakzouk** [comment]
also adding tailwindcss instead of bootstrap that would be awesome

**Comment by axtg** [comment]
And while we're dreaming, Laravel Sanctum instead of JWT?

**Comment by h-zone** [comment]
undersign

**Comment by cretueusebiu** [comment]
I'll definitely look into it soon (Laravel 8 + Vue 3).
As for Tailwind CSS, I think we could use some of the UI from Jetstream.

**Comment by cretueusebiu** [comment]
Working on https://github.com/cretueusebiu/laravel-vue-spa/pull/289
