### ISSUE TITLE
File structure and CRUD

### ISSUE THREAD

**Issue by jbonnett92** [cretueusebiu/laravel-vue-spa#29]
Hi,
I was wondering how this file structure would work with CRUD requests.
I created pages for users like so:
![File structure](https://i.imgur.com/8wlABej.png)
And I also created a module called users with all the funtionality. Although I feel it is the wrong approch to this structure. Is it possible you could add some code to show how to do this correctly?

Also what if I try to "show" a user and the API returns a 404? I find that there is no way to handle it apart from redirect to the page not found page, which isn't what I want to do. Instead I'd like to keep the URL the same and display the page not found.

Thanks for any help in advance.
Jamie

**Comment by cretueusebiu** [comment]
I use the same structure as in your screenshot. If you want to catch errors from your api, and still keep the same page just use a try catch for the axios request and show the appropriator message in that page or maybe an alert.
