### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by ayoubkhan558** [cretueusebiu/laravel-vue-spa#290]
When I tried to run the project using `npm run hot`
It gives this error, Any idea why?

![image](https://user-images.githubusercontent.com/20210961/97828691-b13cb400-1c7c-11eb-8e21-c640e093f912.png)

**Comment by cretueusebiu** [comment]
`npm run hot` seems to be broken...

**Comment by bishoyromany** [comment]
I just tried it now, ```npm run hot``` works fine with hot reload, but you need to run ```php artisan serve``` with it to access the website with hot reload feature.

**Comment by cretueusebiu** [comment]
Fixed in 6.0
