### ISSUE TITLE
Refusing to load or fire a custom js script file

### ISSUE THREAD

**Issue by samsperd** [cretueusebiu/laravel-vue-spa#293]
Hello I tried using a custom theme [CoolAdmin Template](https://github.com/puikinsh/CoolAdmin) instead of the default template that came with the project but one of the script file refused to load or work [main.js](https://github.com/puikinsh/CoolAdmin/blob/master/js/main.js), therefore hamburger menus are not working, sidebar and dropdown menus are also not working.
I tried using laravel mix to compile the js code into app.js, even tried importing the file into app.js and the vue components but it didn't work.

I would have thought this problem was from the script itself but it works perfectly in the template and also with a plain simple laravel project. So I feel like the app.js is refusing this particular script from working
`
      
    (function ($) {
       
      // USE STRICT
        
      "use strict";

    // Dropdown 
     try {
     var menu = $('.js-item-menu');
     var sub_menu_is_showed = -1;

    for (var i = 0; i < menu.length; i++) {
      $(menu[i]).on('click', function (e) {
        e.preventDefault();
        $('.js-right-sidebar').removeClass("show-sidebar");        
        if (jQuery.inArray(this, menu) == sub_menu_is_showed) {
          $(this).toggleClass('show-dropdown');
          sub_menu_is_showed = -1;
        }
        else {
          for (var i = 0; i < menu.length; i++) {
            $(menu[i]).removeClass("show-dropdown");
          }
          $(this).toggleClass('show-dropdown');
          sub_menu_is_showed = jQuery.inArray(this, menu);
        }
      });
    }
    $(".js-item-menu, .js-dropdown").click(function (event) {
      event.stopPropagation();
    });

    $("body,html").on("click", function () {
      for (var i = 0; i < menu.length; i++) {
        menu[i].classList.remove("show-dropdown");
      }
      sub_menu_is_showed = -1;
    });

    } catch (error) {
    console.log(error);
    }

     var wW = $(window).width();
    // Right Sidebar
    var right_sidebar = $('.js-right-sidebar');
    var sidebar_btn = $('.js-sidebar-btn');

    sidebar_btn.on('click', function (e) {
      e.preventDefault();
      for (var i = 0; i < menu.length; i++) {
        menu[i].classList.remove("show-dropdown");
      }
      sub_menu_is_showed = -1;
      right_sidebar.toggleClass("show-sidebar");
    });

    $(".js-right-sidebar, .js-sidebar-btn").click(function (event) {
      event.stopPropagation();
    });

    $("body,html").on("click", function () {
      right_sidebar.removeClass("show-sidebar");

    });
`
 Please help, is there any other way I can get this script to work or fire up. [Link of this question on stackoverflow](https://stackoverflow.com/questions/64714022/laravel-vue-spa-custom-js-script-refusing-to-work/64714493#64714493)
Thanks

**Comment by cretueusebiu** [comment]
You'll have a bad time using jQuery with this project or Vue in general.

**Comment by samsperd** [comment]
@cretueusebiu I just started using this project, what do you mean tho?

**Comment by cretueusebiu** [comment]
Try to limit you jQuery per component, don't use it globally because the DOM changes and it will break your scripts.
