### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by NegativeIQ** [cretueusebiu/laravel-vue-spa#297]
Error happens at install
```
    0 [>---------------------------]    0 [>---------------------------]Generati
ng optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In PackageManifest.php line 131:

  Undefined index: name


Script @php artisan package:discover --ansi handling the post-autoload-dump even
t returned with error code 1

C:\Users\Ice\Desktop>
```

Log
[https://gist.github.com/NegativeIQ/ffeadbbfdea891868558245c71705efb#file-laravel-2020-11-14-txt](url)

**Comment by nikolays93** [comment]
I got a same error.  Did you fix it?

**Comment by nikolays93** [comment]
I wrote ```if (!isset($package['name'])) return [];```
before ```return [$this->format($package['name']) => $package['extra']['laravel'] ?? []];``` in a ```PackageManifest.php```

But i don't know right this to do.. And i got a new error: ```The Mix manifest does not exist.```

**Comment by cretueusebiu** [comment]
It only supports [PHP >= 7.3](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/composer.json).
