### ISSUE TITLE
Role permission

### ISSUE THREAD

**Issue by josendulip** [cretueusebiu/laravel-vue-spa#299]
How to create new role permission?

**Comment by GeoffreyOlivier** [comment]
Yes, I would like to know too and also how did you add another properties (lastname, phone, ..)
Thanks

**Comment by vedatkurtay** [comment]
Hey there, for Role or Permissions you should check the Spatie Permission package or default Laravel Gate system. 
If you want to add more field in registration form you can check this article :[ Laravel Customize ](https://laraveldaily.com/9-things-you-can-customize-in-laravel-registration/)
