### ISSUE TITLE
Error deploying  the application

### ISSUE THREAD

**Issue by passkok** [cretueusebiu/laravel-vue-spa#304]
Thank you for the laravel-vue-spa template. it has been very helpful to me. 
But I have dificulties deploying the application (without any modification of source code). 
I have execute :
- npm install
- npm run prod

But I have these errors : 

GET http://localhost/dist/css/app.bfab7a.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost/dist/js/app.b973ac.js net::ERR_ABORTED 404 (Not Found)

please help.
![Capture](https://user-images.githubusercontent.com/61202516/102554354-f8fc8b00-40c4-11eb-858d-7084ef3b04b3.PNG)

**Comment by NolPixel** [comment]
You need to run `php artisan serve` ... Then goto Listening page, usually http://localhost:8000
