### ISSUE TITLE
Update laravel mix 6

### ISSUE THREAD

**Issue by DasdWaller** [cretueusebiu/laravel-vue-spa#307]

**Comment by cretueusebiu** [comment]
I've tried that but unfortunately it breaks everything... 
If someone could PR it that would be great!

**Comment by h-zone** [comment]
mix 6 is too raw. even out of the box, he does not understand everything. wach/poll behave unpredictably, for example. and this, I repeat, is out of the box.
lets wait some months?

@cretueusebiu can you make sseparate builder based on webpack@latest - may be it is more useful, than dubiousdubious wrappers?

**Comment by cretueusebiu** [comment]
@h-zone I think I'll try Vite first since it's so much faster than webpack.

**Comment by vahidalvandi** [comment]
mix 6 work with vue like bellow

`mix.js('asset/app.js'), 'public/js').vue()`

**Comment by Zelig880** [comment]
I have a repository that started from this started pack, and has now been updated to use laravel 8 and laravel-mix 6.

The config file need to change quite a bit (also hot reload now works).

If anyone wants to see it the link is here: https://github.com/Zelig880/BooksBank/blob/main/webpack.mix.js

**Comment by cretueusebiu** [comment]
Fixed in 6.0
