### ISSUE TITLE
Cannot add new language - Sanctum branch

### ISSUE THREAD

**Issue by cristidd** [cretueusebiu/laravel-vue-spa#309]
I tried adding a new language by adding a new json file in the lang folder (it.json), and i copied the same structure from en.json, but the new language does not show up in the language dropdown.  I also tried deleting a translation file (zh-CN.json) but CN is still displayed on the frontend.  Probably i am missing something.

**Comment by h-zone** [comment]
if there are no pants in the closet, but you want to wear them, then you probably need to buy these pants.

search in configs.

**Comment by cristidd** [comment]
> if there are no pants in the closet, but you want to wear them, then you probably need to buy these pants.
> 
> search in configs.

I completely forgot to look in the config file. Thank you for the help!
