### ISSUE TITLE
sanctum branch bug

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#310]
register => autologin  => will not refresh navbar.
still login/register links (guest mode) until page refresh by F5.

**Comment by h-zone** [comment]
`verify link` toggles auto login (as described at first post), but  not real verify email page
![1](https://user-images.githubusercontent.com/1150044/107629723-944c4f80-6c73-11eb-99d8-6d298d54f0d0.jpg)

**Comment by cretueusebiu** [comment]
Moving to #325
