### ISSUE TITLE
Premium Laravel-Vue SPA

### ISSUE THREAD

**Issue by cretueusebiu** [cretueusebiu/laravel-vue-spa#316]
I'm planning to launch a premium Laravel-Vue SPA starter kit this ~~summer~~ fall and I'd like to know few things you'd expect from it. 

In short, it will consist of 2 apps, the user facing one and an admin dashboard where you can manage everything.

Consider answering this short questionnaire: https://forms.gle/rb2oh24WhNzWiEveA

**Comment by vahidalvandi** [comment]
please use official bootstrap 5 for ui

**Comment by ezequiel9** [comment]
@cretueusebiu I have used it many times and its great! Thanks.

When do you reckon you will have the premium version?

**Comment by cretueusebiu** [comment]
I was hoping that Nuxt 3 would be out by now so I can use it along with Vue 3 (and have SSR).
But since it was delayed a bit, now I'm thinking maybe I'll just go with Vite and Vue 3.

So I guess now I'm hoping for a late fall release.
