### ISSUE TITLE
cannot find fs dependency

### ISSUE THREAD

**Issue by samsperd** [cretueusebiu/laravel-vue-spa#319]
Hello I am trying to add site maps to this application using [Vue-router-sitemaps](https://github.com/40818419/vue-router-sitemap), but I am getting an error in my console concerning fs dependency not being found, This is the error
` 
This dependency was not found:

* fs in ./node_modules/sitemap/lib/sitemap.js, ./node_modules/vue-router-sitemap/dist/index.js
`

**Comment by cretueusebiu** [comment]
This is from vue-router-sitemap, so please check with that package.

**Comment by samsperd** [comment]
Please can you suggest a better package to build a dynamic sitemap for this package. I’m out of options.

**Comment by samsperd** [comment]
> This is from vue-router-sitemap, so please check with that package.

@cretueusebiu Please can you suggest a better package to build a dynamic sitemap for this package. I’m out of options.
