### ISSUE TITLE
Socialite integration

### ISSUE THREAD

**Issue by VerzatileTom** [cretueusebiu/laravel-vue-spa#32]
Hello! How do you integrate Laravel socialite with this?

**Comment by cretueusebiu** [comment]
You could add a route in web.php before any other routes:

```php
Route::get('oauth/facebook', 'OAuthController@facebook');
Route::get('oauth/facebook/callback', 'OAuthController@facebookCallback');
```

Then in the `facebookCallback` method, just inject the Socialite user into the view:

```php
return view('index', ['socialiteUser' => $user]);
```
Next in scripts.blade.php you can add the `$socialiteUser` to the `$config` variable.

Now define the same route in `routes.js` and you can access the Socialite user with `window.config.socialiteUser`.
