### ISSUE TITLE
JWT Sanctum

### ISSUE THREAD

**Issue by MathiasWeisheit** [cretueusebiu/laravel-vue-spa#320]
Hi, is it possible to replace JWT with Laraval's sanctum?

**Comment by calebanthony** [comment]
Laravel Sanctum doesn't utilize JWT, it utilizes sessions under the hood. From the docs:

> For this feature (SPA Authentication), Sanctum does not use tokens of any kind. Instead, Sanctum uses Laravel's built-in cookie based session authentication services.

**Comment by cretueusebiu** [comment]
Moving to #325
