### ISSUE TITLE
Pre-rendering to improve SEO

### ISSUE THREAD

**Issue by ezequiel9** [cretueusebiu/laravel-vue-spa#322]
Before just congrats for your project, its great!

- After some time running this spa, I am trying to get a pre-render html or SSR  to improve seo. I have tried but I can't get it yet. I have used this package: 

```javascript

        new HtmlWebpackPlugin({
            title: 'PRODUCTION prerender-spa-plugin',
            template: path.resolve(__dirname, './public/index.html'),
            filename: path.resolve(__dirname, './public/dist/index.html'),
        }),
        new PrerenderSPAPlugin({
            staticDir: path.join(__dirname, './public/dist'),
            routes: [ '/', '/prices', '/faqs' ],

            renderer: new Renderer({
                inject: {
                    foo: 'bar'
                },
                headless: true,
                renderAfterDocumentEvent: 'render-event'
            })
        })

```

But doesn't work because I guess it generates an index.html and we use index.php?

Is there some approach that you can give us to sort this? Thanks.

**Comment by cretueusebiu** [comment]
When it comes to SEO you have to go with Nuxt.js (https://github.com/cretueusebiu/laravel-nuxt).
Not sure how you'd go with prerendering though...

**Comment by vahidalvandi** [comment]
better way is livewire

**Comment by cretueusebiu** [comment]
@ezequiel9 I've put together an example with Puppeteer:
https://github.com/cretueusebiu/laravel-vue-spa/tree/ssr

```bash
npm run build
npm run ssr-server
```
It creates a browser instance and then for each http request it makes a call with puppeteer to render that page and serve it back.

https://developers.google.com/web/tools/puppeteer/articles/ssr

**Comment by ezequiel9** [comment]
@cretueusebiu Awesome! I'll try this and let you know, thank you!
