### ISSUE TITLE
the-control-group/voyager Integration

### ISSUE THREAD

**Issue by andreicvasniuc05** [cretueusebiu/laravel-vue-spa#33]
Hi. I want to use Voyager as admin panel but have a lot of issues after installation. How can I do this?
https://github.com/the-control-group/voyager

**Comment by cretueusebiu** [comment]
Sorry but it's out of the scope of this project.

**Comment by andreicvasniuc05** [comment]
I installed all.. but laravel's auth doesn't work

**Comment by cretueusebiu** [comment]
This project uses the api driver by default. You'll have to change it back to web.

**Comment by devig** [comment]
How to use both auth in this case?

**Comment by cretueusebiu** [comment]
You should be able to use it now, but you would need 2 separate logins.

**Comment by mepsd** [comment]
can anyone tell me how could i add two logins?
