### ISSUE TITLE
[HELP] multi router guard

### ISSUE THREAD

**Issue by namdp06** [cretueusebiu/laravel-vue-spa#34]
I can not make router with 2 guard user and admin in the same routes.js
it always return to the default guard from router/index.js
What I need to do:
- I have directory like so: 
-- aaaa/bbbb/cccc => stand for admin page
-- aaaa/dddd/eeee => stand for user page
- When I access aaaa/dddd/eeee without login, it always check auth from aaaa/bbbb/cccc
- I had tried to separate router and user_router but it said $nextTick was null.
This is just a half of my project, it requires 4 types of users to login using different path. 
- Path 1: aaaa/bbbb/cccc => auth user type 1
- Path 2: aaaa/dddd/eeee => auth user type 2
- Path 3: ffff/bbbb/cccc => auth user type 3
- Path 4: ffff/dddd/eeee => auth user type 4

Could you please help me a guide to make this type of router?

**Comment by cretueusebiu** [comment]
Nested guards won't work because only the last one will apply. 
Instead create a new admin guard that also checks if the user is authenticated: 

```javascript
import store from '~/store'

function adminGuard (routes) {
  return routes.map(route => {
    return {
      ...route,
      beforeEnter (to, from, next) {
        if (!store.getters.authCheck) {
          next({ name: 'login' })
        } else {
          if (store.getters.authUser.role !== 'admin') {
            next({ name: 'home' })
          } else {
            next()
          }
        }
      }
    }
  })
}
```

Then just add your routes:

```javascript
...adminGuard([
  { path: '/admin', name: 'admin', component: require('~/pages/admin.vue') }
]),
```

**Comment by cretueusebiu** [comment]
With the latest update you can have multiple middleware (guards) per route.
https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/router/routes.js

**Comment by namdp06** [comment]
@cretueusebiu thank you so much
