### ISSUE TITLE
how about basic tutorial ?

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#4]
- how to create a new page and integrate it to the project?
- how to check user authenticated or not?
- how to async query backend for the data from custom page, previously created?
just simple and basic tutorial without explaination.

**Comment by cretueusebiu** [comment]
This is just a basic example that I use when creating spa projects. It's not like a framework or something like that. 

What I've recently discovered is [Nuxt.js](https://nuxtjs.org), which is an actual framework if you want to create a SPA. I've used it a bit with Laravel and works really nice.  You should give it a try.
