### ISSUE TITLE
Handling permissions

### ISSUE THREAD

**Issue by Remo** [cretueusebiu/laravel-vue-spa#42]
I'll add support for permissions and was wondering if there's a way to include this in your repo. If we could find an approach that's fine for both of us I'd try to work on a PR.

My idea is to include laratrust and put the complete list of permission keys available to the user in `auth/user`. I'd then assign 0-n permission keys to each route to only show the ones available to the user.

In a further version we could even add a simple backend so that one could manage users and roles without writing any code.

What are your thoughts on that?

**Comment by cretueusebiu** [comment]
I prefer [spatie/laravel-permission](https://github.com/spatie/laravel-permission), but I think adding roles and permissions would be too much for this template. I'd like to keep it simple for now.

Thanks for consideration.

**Comment by Remo** [comment]
Sure things!
