### ISSUE TITLE
Using For Multi Domain Project to share session and cookie

### ISSUE THREAD

**Issue by Quadriphobs1** [cretueusebiu/laravel-vue-spa#44]
How do you configure the project to be used for multiple domain project i have tried laravel recommended approach but doesnt seems to work and i have been working on this for like 2 days now. Any help on thisor any hint at all

**Comment by cretueusebiu** [comment]
I think you should check the vue router and see if it supports sub domain routing. 
The client part is decoupled from Laravel so won't work that way.

**Comment by Quadriphobs1** [comment]
so working on this and digging deep into i noticed that vue-router cannot handle sub-domain routing i just have to do it with serverside routing, which i was able to use in laravel, s o using laravel mix, i was able to have sub domain, using same project to access the same folder but different route group, using laravel ix i was able to split the vue resource for each domain, so now i have in the resources folder, a folder for the main site another for the subdomain and using different interface and assets, also in the views folder i have different laravel view which is rendered for each domain, but the issue i am facing now is sharing same session & cookie between the sub domain and main domain, for now in my main domain i have same thing in the vue resource folder duplicated to the sub domain, and do some little twerking for how they are been compile but the issue i seem to be facing now is how the session can be shared, i have set the laravel to be a wildcard session, but not working, and i guess from the issue might from the `loginController` which uses this `$this->guard()->setToken($token);` 
i know this is been used to set the token when logged so that vue will know the user is logged but but i dont really understand how this works, 

i hope anyone could understand me and help out am really confused now, 

i have to make this work

**Comment by cretueusebiu** [comment]
This project doesn't use the Laravel session, it uses [JWT](https://github.com/tymondesigns/jwt-auth). 

You'll have to remove that and revert back to the default Laravel session authentication driver. This will require some work since now everything is built with a JWT token.
