### ISSUE TITLE
Sub Domain Session Sharing in refference to this #44

### ISSUE THREAD

**Issue by Quadriphobs1** [cretueusebiu/laravel-vue-spa#45]
I Have project i would like to share session between, 

The project is using one laravel app, which means it is using the same app key so i am using laravel route group for routing the sub domain. like this
`Route::group(['domain' => 'example.test'], function () {
    Route::get('{path}', function () {
    	return view('index');
	})->where('path', '(.*)');
	
});

Route::group(['domain' => 'dashboard.example.test'], function () {
    Route::get('{path}', function () {
    	return view('dashboard.index');
	})->where('path', '(.*)');
});` 

> Notice i am using different view for the two domains.

And in my laravel resource folder i have for the main domain which is using the assets and another folder for the sub domain which is using the dashboard with the duplicate of whats in the assets folder and some little changes in the file to watch for the files in the directory alone thanks to laravel mix for that, in short i different views for each domain, but when login on the main domain or the sub domain, the cookie is suppose to be shared but not sharing, think i can get a little help

**Comment by cretueusebiu** [comment]
This project doesn't use the Laravel session, it uses [JWT](https://github.com/tymondesigns/jwt-auth). 

You'll have to remove that and revert back to the default Laravel session authentication driver. This will require some work since now everything is built with a JWT token.
