### ISSUE TITLE
Vue SSR

### ISSUE THREAD

**Issue by aymenpeak** [cretueusebiu/laravel-vue-spa#5]
Hi,
Can we setup the vue SSR with this template? i'm a little bit confused...

**Comment by cretueusebiu** [comment]
No, it doesn't work with PHP. If you want SSR check out [Nuxt.js](https://nuxtjs.org). Works very well with Laravel.

**Comment by milo526** [comment]
With the Vue 2.5.0 update SSR has become available.  
For example see https://vuejsdevelopers.com/2017/11/06/vue-js-laravel-server-side-rendering/

Are there any plans on implementing this?

**Comment by cretueusebiu** [comment]
I've looked over that a while ago, might give it a try. 
However if you want SSR you should try Nuxt.

**Comment by cretueusebiu** [comment]
If you're intrestead in SSR, I just published [laravel-nuxt](https://github.com/cretueusebiu/laravel-nuxt).
