### ISSUE TITLE
give example

### ISSUE THREAD

**Issue by Haizone** [cretueusebiu/laravel-vue-spa#51]
hi
u can wirte example how to get and send to the database
and how to use the route?

give us a few pages to see to to work with that more :)

great work!

**Comment by cretueusebiu** [comment]
There are examples for login, register, password reset, settings:
[resources/assets/js/router/routes.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/router/routes.js)
[resources/assets/js/pages](https://github.com/cretueusebiu/laravel-vue-spa/tree/master/resources/assets/js/pages)
