### ISSUE TITLE
Whether you can load the js script as needed.

### ISSUE THREAD

**Issue by jxZhangLi** [cretueusebiu/laravel-vue-spa#52]
Use methods like vue-cli.
```javascript
const Statistics = r => require.ensure([], () => r(require('@/components/statistics/statistics')), 'Statistics')
```

**Comment by cretueusebiu** [comment]
Dynamic imported  pages are not supported. For that I have [laravel-nuxt](https://github.com/cretueusebiu/laravel-nuxt).

**Comment by nachodd** [comment]
Sorry to ask, but.. why isn't supported? it'd be a great additon!

**Comment by cretueusebiu** [comment]
It just breaks the current layout system when you switch from one layout to another.

**Comment by cretueusebiu** [comment]
This should do it https://github.com/cretueusebiu/laravel-vue-spa/commit/45bfdd801662b5fbc55b500f3df1ecfdc6bacf3d
