### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by Budy-Love** [cretueusebiu/laravel-vue-spa#53]
Hello,

if you click remember me, i expected that a remember token is stored in the user table and used if session is expired to keep session alive.

**Comment by cretueusebiu** [comment]
The token is stored in a cookie because the Laravel session is not used.
[resources/assets/js/store/modules/auth.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/store/modules/auth.js#L22)

**Comment by Budy-Love** [comment]
Ok thanks, but how it's possible to stay logged in? (session expired->cookie token used to stay logged in)

**Comment by cretueusebiu** [comment]
You don't have a session anymore. A token is stored in the cookie, either until you close the browser or if you click remember me, forever. 

However by default time to live of the JWT token is only 60 minutes. 
So if you close the browser and open if after 60 minutes, it will try to fetch the user from server, but the token is invalid and will be removed from the cookie. 

You can .env add `JWT_TTL=20160` 
See https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php

**Comment by Budy-Love** [comment]
Thanks for explanation.

**Comment by h-zone** [comment]
@cretueusebiu 
but can we store and use remember_token in cookies?
then compare with database one when fetching user?
How unsafe is this?
