### ISSUE TITLE
Previous page and layout problem

### ISSUE THREAD

**Issue by yeungc** [cretueusebiu/laravel-vue-spa#55]
Hi, just found an issue and don't know if that is a bug or not.

I created a new layout called "auth" for login and register page. Which mean if I have logged in, when I click logout button, I will redirect to login page and layout will change from "app" to "auth".

On this moment if I go back to previous page, it will redirect me to login page again, however layout will be "app" but not "auth".

I think the reason is "setLayout" function run before middleware, but I have no idea how to fix it.

**Comment by cretueusebiu** [comment]
The latest version just uses components for layouts and direct component middleware.

**Comment by yeungc** [comment]
Hi, don't think that is a good idea, for example if I have a search bar in top menu and inputted something, old layout system will keep it when I go to next page in same layout, only "child" component will be updated.

It's also not good for performance, even next page have same layout, all elements in body need to generate again.

In my opinions, this change make layout system worse than before.

**Comment by cretueusebiu** [comment]
You're right about the layout, it's back now. Didn't thought about that. 
The problem with layouts not changing when you go back was from how the middleware worked before. But it's fixed now.

**Comment by yeungc** [comment]
Thank you so much, layout is now works fine :)
