### ISSUE TITLE
Socialite GitHub setup

### ISSUE THREAD

**Issue by rafal-olszewski** [cretueusebiu/laravel-vue-spa#56]
I have issue while trying to setup github as my socialite provider, here's my github app config:
![image](https://user-images.githubusercontent.com/29777438/35242830-15b226ea-ffbb-11e7-8254-4c961db47a1e.png)

And my `.env` file is filled with client ID and client secret. The button appears on login and registration page, few times it created a popup for oauth, but after few times it stoped showing at all.

The config is almost untouched, except for the essentials like database connection and such.

**Comment by cretueusebiu** [comment]
Sometime the browser will block popups and you have to manually allow it:

![screenshot](https://user-images.githubusercontent.com/1517945/35243054-3f789cbc-ffc4-11e7-9974-5637d7f4dd1a.png)

**Comment by rafal-olszewski** [comment]
I had this at the first try, but then checked to Always allow pop-ups.

I'm sorry, forgot to mention this, I did it before any pop-ups begun to show.
