### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by cretueusebiu** [cretueusebiu/laravel-vue-spa#57]
Write a quick guide for pages, layouts, routes and middleware.

**Comment by redaced** [comment]
hello why removed middleware code form source code  ?

**Comment by yeungc** [comment]
Hi, don't think new layout system is a good idea, for example if I have a search bar in top menu and inputted something, old layout system will keep it when I go to next page in same layout, only "child" component will be updated.

It's also not good for performance, even next page have same layout, all elements in body need to generate again.

In my opinions, this change make layout system worse than before.

**Comment by cretueusebiu** [comment]
@redaced It was removed from `routes.js` and you have to define it on the component level in order to fix an issue when you click back in your browser and the layout was not changing correctly.

@yeungc You're right about the layout, it's back now. Didn't thought about that. The problem with layouts not changing when you go back was from how the middleware worked before. But it's fixed now.

**Comment by firmantr3** [comment]
hi, i'm new to SPA apps and want to try one from this repo, i've followed the instruction but i got an error:

```
.Uncaught (in promise) Error: Cannot find module './id'.
    at webpackAsyncContext (http://localhost:8000/js/app.js:23758:25)
    at _callee$ (http://localhost:8000/js/app.js:11501:43)
    at tryCatch (http://localhost:8000/js/app.js:16347:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/js/app.js:16581:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/js/app.js:16399:21)
    at step (http://localhost:8000/js/app.js:11472:191)
    at http://localhost:8000/js/app.js:11472:437
    at new Promise (<anonymous>)
    at http://localhost:8000/js/app.js:11472:99
    at loadMessages (http://localhost:8000/js/app.js:11523:17)
```

i have no idea how to fix this

**Comment by bhoggett** [comment]
+1 for the Guide.  Understanding how a template works is critical to its usefulness.

**Comment by hobby10** [comment]
is there any guide, please ?

**Comment by hobby10** [comment]
could i use this project as a web with vuejs and also as a restful api for mobile app ... i tried to make calls using postman for login but i get nothing ?!!

**Comment by mercuryskies** [comment]
@cretueusebiu Hi! Thank you for this project. Could you please clarify how to deauthorize logged user

**Comment by luhegi** [comment]
@cretueusebiu how to make facebook open graph able to get our defined meta?

**Comment by cretueusebiu** [comment]
@luhegi this project has nothing to do with Facebook.

**Comment by MerrySean** [comment]
Is Anyone Writing a quick guide?

**Comment by MerrySean** [comment]
I didn't really understand this part.

`
  computed: mapGetters({
    user: 'auth/user'
  })

`
This line of codes can be found in 
**/Resources/assets/js/layouts/default.vue**

**Comment by cretueusebiu** [comment]
@MerrySean See the [vuex docs](https://vuex.vuejs.org/en/getters.html#the-mapgetters-helper).

**Comment by MerrySean** [comment]
@cretueusebiu  Hi, I was just wondering where did you get the "**.role**" in line 4 in this file

 laravel-vue-spa/resources/assets/js/middleware/admin.js

because I was looking for it on the user's table which was stored in the database, there was no Role column, I also looked at the model of User, I only saw that you append the "photo_url" but not the Role? 

so where did you get it?

**Comment by cretueusebiu** [comment]
@MerrySean that's not implemented, it's there just as an example.

**Comment by modemb** [comment]
i have actually added French on my end go to config app and add a new language there, it will be added to the drop-down

**Comment by ZHamsiou** [comment]
Thanks, it's done,  but I try to figure out how to bind my js file in the public folder so it can display the spa in French. Any advice?

**Comment by cretueusebiu** [comment]
The translation files should be placed in `resources/assets/js/lang` in order to be imported with webpack's dynamic import. Then you'll have to defined them in `config/app.php`.

**Comment by ZHamsiou** [comment]
Well, there are some probs I had noticed :
First,  I add the french file that I named "lang-fr.6eef95981ab9638804ce.js" in /public/js, the translation files in resources/assets/js/lang, I defined them in config/app.php 
like here -->
'locales' => [
        'en' => 'EN',
        'zh-CN' => '中文',
        'es' => 'ES',
        'fr' => 'FR'
I also add that in this file : /public/js/app.js -->
line 89 

script.src = __webpack_require__.p + "js/" + ({"0":"lang-zh-CN","1":"lang-es","2":"lang-en","3":"lang-fr"}

In addition, I update the file /resources/assets/js/componets/Navbar.vue ->
line 29 
<router-link :to="{ name: 'settings.profile' }" class="dropdown-item pl-4">

(By the way, I work with wamp) And when I enter in my command line: php artisan serve so I can use the localhost:8000 address. The application makes a long time to process and the result is a full blank page. Can you tell me if I miss something, please ?

Secondly, i don't think that the json files in /resources/assets/js/lang are useful. Cause, when you change the content of those files, it that does not effect what you see with the display. The only files that change the text you can see on screen are in the "/public/js" folder

**Comment by cretueusebiu** [comment]
@ZHamsiou You don't create / update dist files. Those are generated by the build scripts. Just add them as I said in my previous comment.
