### ISSUE TITLE
controller not return any data

### ISSUE THREAD

**Issue by TechShankar** [cretueusebiu/laravel-vue-spa#60]
I'm created another table to store articles and this is my controller. this not returns any data from database please help me.

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Article::orderBy('id', 'DESC')->get();
    }

this my route : Route::resource('/article', 'ArticleController');

**Comment by cretueusebiu** [comment]
Sorry, this question is not related to this project. Check for errors in your console

**Comment by TechShankar** [comment]
sir, i'm asking for this project. please see my stackoverflow question =
https://stackoverflow.com/questions/48606355/laravel-vuex-not-reterned-data-from-database
