### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by jswails** [cretueusebiu/laravel-vue-spa#61]
I just loaded up your project to take a look at it and its unusable at this point. When you go to register from a fresh build nothing happens. Using php7.2 with latest laravel. You might want to try a fresh build yourself on a new environment to see. I tried it on two separate machines here.

**Comment by cretueusebiu** [comment]
If you installed via git clone or download, run `php artisan key:generate` and `php artisan jwt:secret`.

**Comment by jswails** [comment]
Thanks I'll give that a try

**Comment by jswails** [comment]
Well I tried that. Still nothing. No errors. Ju st does nothing when I hit
submit on register. Very curious. Thanks for the response though.

**Comment by cretueusebiu** [comment]
Have you checked the logs or the console for errors ?

**Comment by jswails** [comment]
my bad. It was my apache server. Thank you for checking back. Its been so long since I had to configure a new apache server I forgotten about mod rewrite issues and apache with laravel

**Comment by cretueusebiu** [comment]
Try Laravel Valet.

**Comment by MitnickCondor** [comment]
Maybe I'm blind ... but I cant find the "register" method of the RegisterController.php ... maybe that's why I get the ERROR 500? ^^' ... Btw. I'm on a windows machine. Thanks for any help!
