### ISSUE TITLE
npm run production missing "webpackJsonp"

### ISSUE THREAD

**Issue by lorenzofaresin** [cretueusebiu/laravel-vue-spa#62]
Running "**npm run watch**" all works
but running "**npm run production**" I get blank page and on console only this error:

```
app.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at app.js:1
(anonymous) @ app.js:1
```

**Comment by lorenzofaresin** [comment]
solved with:
**APP_ENV=production**

on .env

sorry

**Comment by piotrkochan** [comment]
Still, it is goofy that `production` setting must be used to development...
