### ISSUE TITLE
User token expiration

### ISSUE THREAD

**Issue by sammagee** [cretueusebiu/laravel-vue-spa#63]
This may just be me not understanding how it works. When I login with "remember" enabled, it correctly sets the cookie, and the cookie says it will expire in a year, but after about 10 minutes of being logged in, and refreshing the page, it logs out, saying the session has expired.

**Comment by cretueusebiu** [comment]
The ttl of the token is 60 minutes [by default](https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L90). So even if the cookie is set for one year the token can still expire sooner.

**Comment by sammagee** [comment]
Perfect, I overlooked this. Thanks for the response!
