### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by egyptik** [cretueusebiu/laravel-vue-spa#64]
Upgrade package to run on Laravel 5.6

**Comment by egyptik** [comment]
See: #65

**Comment by egyptik** [comment]
Merged 👌🏻

**Comment by cretueusebiu** [comment]
Not sure how the tests passed since [tymon/jwt-auth](https://github.com/tymondesigns/jwt-auth/blob/develop/composer.json) doesn't yet support Laravel 5.6.

When I try to install it locally I get an error that jwt-auth is not compatible with 5.6.

**Comment by cretueusebiu** [comment]
There is a pull request https://github.com/tymondesigns/jwt-auth/pull/1469 but was not merged yet.

**Comment by egyptik** [comment]
That's strange..? Worked perfectly fine for me...

All unit tests and dusk passed, was able create account/sign in and use change every option under the settings pages.

**Comment by cretueusebiu** [comment]
The tests passed because where still running on 5.5. https://travis-ci.org/cretueusebiu/laravel-vue-spa/jobs/338681910

The composer.lock file still has the old dependencies.

Run `composer update` and you'll see the error.

**Comment by egyptik** [comment]
Ahh, I see. Didn't think about the lock file. I just updated the dependencies and ran `composer install` 😓

**Comment by cretueusebiu** [comment]
I'll revert it since people still clone the repo instead of using composer for installing the project.  Will wait for jwt to be fixed.

**Comment by egyptik** [comment]
See #67. A new release for jwt-auth supporting L5.6 has been tagged. Should work this time :)
