### ISSUE TITLE
Login and register tweak

### ISSUE THREAD

**Issue by kwame101** [cretueusebiu/laravel-vue-spa#69]
Hi I'm creating a spa project with your laravel vue template. I created a new page called get started which contains a simple form to allow user to enter their email address and submit it. I want to tweak the following process 
- I want to tweak the login and register process to redirect user if they haven't typed in their email from get started page (regarding they just typed in /login or /register url)
- Redirect user to login if he's email is registered else register page. - I've somehow done it this but I'm not sure redirect is best way, maybe load the component dynamically? 

I know this is not where to ask for help but could you please guide me as to how I could approach this situation and also do you have discord? 

Sorry for the long message, I've been searching everywhere for this solution but cant get any help and I'm also newish with vue so I thought i would dive right into the fun.

**Comment by egyptik** [comment]
This is done with middleware, or what they call `Navigation guards` in Vue:

https://router.vuejs.org/en/advanced/navigation-guards.html

In this project, the logic for the guards/middleware is located in the `resources/assets/js/middleware` dir. You can define which middleware you'd like to use on a per-page level, using the middleware attribute. 

For example, look at the Login page (`resources/assets/js/pages/auth/login.vue`). You'll see the `middleware: 'guest'` defined there.

**Comment by cretueusebiu** [comment]
A redirect it's fine. You can do it in the `created` method of the login / register components or if you don't event want to initialize the components (while you make the request to the server to determine if the email is taken or not) you can use [component guards](https://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards).
