### ISSUE TITLE
Help me please! Access the laravel public folder

### ISSUE THREAD

**Issue by ericksongmr** [cretueusebiu/laravel-vue-spa#72]
Hello, I am new working with spa, and now I have the inconvenience of showing an image that I have in the public folder of laravel in a component of vue.

Try doing it this way:
`<img class="d-block img-fluid" src="/public/img/carousel/baner1.jpeg" alt="First slide">`
But it does not work.

And if I put in the url the full path tells me that the page has not been found.
`http://localhost:8000/public/img/carousel/baner1.jpeg`

Could you please tell me the correct way to access my files from the public folder or the correct place where I should save them and how to access them? Thanks!!

**Comment by cretueusebiu** [comment]
Use `/img/carousel/baner1.jpeg`

**Comment by gitamgadtaula** [comment]
Hi did you fix the Issue?
