### ISSUE TITLE
Help! Compile new js

### ISSUE THREAD

**Issue by ericksongmr** [cretueusebiu/laravel-vue-spa#73]
Hi, thank you in advance for your help and for all this work that you have done that is great.
The problem that I have now is that I have created a custom layout, and I have managed to load everything well including the css, but in the original dashboard it asks me to load the following js:
```
</div>
    <!-- Javascript files-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Main File-->
    <script src="js/front.js"></script>
  </body>
```
The first 2 do not need them because they are already integrated, but the one that says front.js if I need it to work properly.
Try loading it like this in webpack.mix.js:
```
mix
  .js([
'resources/assets/js/app.js',
'resources/assets/js/plugins/front.js'
], 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')

  .sourceMaps()
  .disableNotifications()

if (mix.inProduction()) {
  mix.version()

  mix.extract([
    'vue',
    'vform',
    'axios',
    'vuex',
    'jquery',
    'popper.js',
    'vue-i18n',
    'vue-meta',
    'js-cookie',
    'bootstrap',
    'vue-router',
    'sweetalert2',
    'vuex-router-sync',
    '@fortawesome/fontawesome',
    '@fortawesome/vue-fontawesome'
  ])
}
```
If it compile but the dashboard still does not work as it should, I guess it must be in order and it has to be right after the bootstrap.min.js
I also tried changing the order, first front.sj and then app.js but it did not work either.
I do not know if it should be added in mix.extract but I do not know how to call the js.

So what would be the correct way to compile it so that it appears right after the bootstrap.min.js and the dasboard can work properly? Thanks!

**Comment by cretueusebiu** [comment]
Try importing the script files in the main `app.js` file.
