### ISSUE TITLE
ReferenceError: $ is not defined at

### ISSUE THREAD

**Issue by ericksongmr** [cretueusebiu/laravel-vue-spa#75]
Hi friend, I'm having this problem, when I try to use jquery within my layout
![image](https://user-images.githubusercontent.com/35790384/36820660-fc2d9a14-1cbc-11e8-9025-f38ba7936dfb.png)

I get this error.
![image](https://user-images.githubusercontent.com/35790384/36820652-ec4d4bf8-1cbc-11e8-8ece-1114484c389f.png)

Why do not you recognize me jquery?
How should I solve it?
Normally when I have worked with laravel and vue he has always recognized me jquery without problems.
I hope you can help me as before. Thank you

**Comment by cretueusebiu** [comment]
I don't declare any global variables like Laravel does, so you have to import jQuery.

```javascript
import $ from 'jquery'
```
