### ISSUE TITLE
How to deploy in Linux server

### ISSUE THREAD

**Issue by TechShankar** [cretueusebiu/laravel-vue-spa#76]
Hello sir I'm new in laravel development. I'm created simple project with your laravel-vue-spa template.
This project works wery well in local machine. But server side problem. Please guide me.

**Comment by cretueusebiu** [comment]
Hi, this project already assumes that you are familiar with Laravel and Vue so you deploy it as any other Laravel app. 
You should check the Laravel docs and forums for more info about deployment.
