### ISSUE TITLE
Unable to work npm run watch and production.

### ISSUE THREAD

**Issue by shankhadevpadam** [cretueusebiu/laravel-vue-spa#79]
I have clone and configure this repo. But when i run the npm run watch and production command there is error in terminal.
Ubuntu version : 16.04
npm version: 5.6.0
node version: 9.8.0

**Comment by cretueusebiu** [comment]
What error?

**Comment by shankhadevpadam** [comment]
![screenshot from 2018-03-14 14-47-27](https://user-images.githubusercontent.com/3838722/37392622-bdc3d86c-2796-11e8-9b06-551a63d21a0e.png)

**Comment by shankhadevpadam** [comment]
![screenshot from 2018-03-14 14-49-43](https://user-images.githubusercontent.com/3838722/37392709-0582ab4c-2797-11e8-8e54-fd9f5026a858.png)

**Comment by cretueusebiu** [comment]
Run `yarn` or `npm install`.

**Comment by shankhadevpadam** [comment]
I have already run the yarn or npm install

**Comment by cretueusebiu** [comment]
Try checking with [laravel-mix](https://github.com/JeffreyWay/laravel-mix) since that's what this project is using.

**Comment by shankhadevpadam** [comment]
I have fixed my self adding vue-loader package.

Thanks

**Comment by shankhadevpadam** [comment]
I got this error.
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Root>
```
