### ISSUE TITLE
Suitable for production?

### ISSUE THREAD

**Issue by yammadev** [cretueusebiu/laravel-vue-spa#8]
I read this is a work in progress. May you provide a to-do list in order to help or to know how much is required for using this template in a production environment? I would like to help, for sure. Let me know.

**Comment by cretueusebiu** [comment]
Sure you can use it in production. It's not like a library, it's more like a boilerplate that I used in some projects.

Lately I've switched to [Nuxt](https://nuxtjs.org/) + Laravel so that's why there's not much activity on this repo.

**Comment by yammadev** [comment]
Thank you anyway, I'll close this issue then, and I hope to do some pull requests in the future, and who knows, maybe to keep supporting this boilerplate.
