### ISSUE TITLE
different layouts

### ISSUE THREAD

**Issue by arturkrysov** [cretueusebiu/laravel-vue-spa#82]
hello

it is possible to have different layouts? like a template for user and another one for admin

thank you

**Comment by cretueusebiu** [comment]
Maybe you could add a new middleware that would set the layout based on the user. Take a look at router/index.js to see how the layout is set.

**Comment by arturkrysov** [comment]
can u please provide a example? and instead of user will be better if was by the router path i take a look where you mentioned and i dont understand how to set layout from middelware
