### ISSUE TITLE
Change articles according to language selected in locale dropdown

### ISSUE THREAD

**Issue by shrikanth003** [cretueusebiu/laravel-vue-spa#84]
The template is working fine with translations from the json file. I have articles table and articles_translations table where articles_translations has a column locale code

In my controller (ArticleController)
```
public function index()
    {
        $locale = Lang::locale();
        // $locale =   Lang::getLocale();
        $articles = Article::withTranslations($locale)->get();
        return $articles;
    }
```
I'm fetching the locale detected on the front end to fetch the articles according to that language from the database

My Article.vue component
```
<template>
    <div>
      <div v-for="article in articles" :key="article.articles">
          <div v-for="translation in article.translations">
              <h4>{{ translation.title }}</h4>
              {{ translation.subtitle }}
              {{ translation.content }}
          </div>
      </div>
    </div>
</template>

<script>
import axios from 'axios'
import { mapGetters } from 'vuex'
  export default {
    layout: 'basic',

    computed: mapGetters({
      locale: 'lang/locale'
    }),

    data: function () {
        return {
            articles: []
        }
    },
    mounted() {
        console.log(this.locale)
        var app = this;
        axios.get('/api/articles')
            .then(response => {
              // JSON responses are automatically parsed.
              this.articles = response.data
            })
            .catch(e => {
              this.errors.push(e)
            })
    }
  }
</script>

```
When i switch the language from english to spanish, the static translations change like the login, register show as "iniciar sesion' and 'registro'. However the dynamic translations from the database do not change they still show english article. Until i do a refresh, which shows the spanish article from the database. How to achieve this without refreshing the page. I  mean how to sync the articles section get change when there is a change in the locale dropdown

I have tried multiple forums but could not get answer for this. I'm stuck at this point as i want to use this template for 3 of my projects and this functionality is crutial in all the three.

**Comment by cretueusebiu** [comment]
As I said in the previous issue, you have to listen for the store changes.

**Comment by shrikanth003** [comment]
i added a watch function and it worked! Thanks
