### ISSUE TITLE
authentication lost on refresh page

### ISSUE THREAD

**Issue by koekaverna** [cretueusebiu/laravel-vue-spa#85]
When the session expired, after login, the user remains authorized only until the page is refreshed
When i restart nuxt it works again (After refreshing the page - the user is authorized)

auth/fetchUser exception
`{ Error: Request failed with status code 401
    at createError (/mnt/c/code/webserver/www/codepr-cabinet/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/mnt/c/code/webserver/www/codepr-cabinet/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/mnt/c/code/webserver/www/codepr-cabinet/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hcGkuY29kZXByLmxvY2FsXC9hcGlcL3VzZXJcL2xvZ2luIiwiaWF0IjoxNTIxMzkwOTcwLCJleHAiOjE1MjEzOTQ1NzAsIm5iZiI6MTUyMTM5MDk3MCwianRpIjoiRmxCQzRyZHBwWVhjVXRhSSIsInN1YiI6MSwicHJ2IjoiODdlMGFmMWVmOWZkMTU4MTJmZGVjOTcxNTNhMTRlMGIwNDc1NDZhYSJ9.gS99eAdEImkEbdhycmLDNyQgxtGQdS9-YbQ8J7rzNXE',
        'Accept-Language': 'ru',
        'User-Agent': 'axios/0.18.0' },
     method: 'get',
     url: 'http://api.codepr.local/api/user',
     baseURL: 'http://api.codepr.local/api',
     data: undefined },
  request:
   ClientRequest {
     domain: null,
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.codepr.local',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 512,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 85339,
        [Symbol(bytesRead)]: 301 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.codepr.local',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 512,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 85339,
        [Symbol(bytesRead)]: 301 },
     _header: 'GET /api/user HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hcGkuY29kZXByLmxvY2FsXC9hcGlcL3VzZXJcL2xvZ2luIiwiaWF0IjoxNTIxMzkwOTcwLCJleHAiOjE1MjEzOTQ1NzAsIm5iZiI6MTUyMTM5MDk3MCwianRpIjoiRmxCQzRyZHBwWVhjVXRhSSIsInN1YiI6MSwicHJ2IjoiODdlMGFmMWVmOWZkMTU4MTJmZGVjOTcxNTNhMTRlMGIwNDc1NDZhYSJ9.gS99eAdEImkEbdhycmLDNyQgxtGQdS9-YbQ8J7rzNXE\r\nAccept-Language: ru\r\nUser-Agent: axios/0.18.0\r\nHost: api.codepr.local\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/api/user',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 401,
        statusMessage: 'Unauthorized',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://api.codepr.local/api/user',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://api.codepr.local/api/user' },
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        authorization: [Array],
        'accept-language': [Array],
        'user-agent': [Array],
        host: [Array] } },
  response:
   { status: 401,
     statusText: 'Unauthorized',
     headers:
      { server: 'nginx/1.10.3 (Ubuntu)',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'cache-control': 'no-cache, private',
        date: 'Sun, 18 Mar 2018 18:47:02 GMT',
        'x-ratelimit-limit': '60',
        'x-ratelimit-remaining': '59' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: 'http://api.codepr.local/api/user',
        baseURL: 'http://api.codepr.local/api',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /api/user HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hcGkuY29kZXByLmxvY2FsXC9hcGlcL3VzZXJcL2xvZ2luIiwiaWF0IjoxNTIxMzkwOTcwLCJleHAiOjE1MjEzOTQ1NzAsIm5iZiI6MTUyMTM5MDk3MCwianRpIjoiRmxCQzRyZHBwWVhjVXRhSSIsInN1YiI6MSwicHJ2IjoiODdlMGFmMWVmOWZkMTU4MTJmZGVjOTcxNTNhMTRlMGIwNDc1NDZhYSJ9.gS99eAdEImkEbdhycmLDNyQgxtGQdS9-YbQ8J7rzNXE\r\nAccept-Language: ru\r\nUser-Agent: axios/0.18.0\r\nHost: api.codepr.local\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/user',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: { message: 'Unauthenticated.' } } }`

**Comment by koekaverna** [comment]
This is a question about laravel-nuxt
Do I need to open the issue in laravel-nuxt project?
Create it here by mistake

**Comment by cretueusebiu** [comment]
I think you forgot to generate the jwt secret.

**Comment by koekaverna** [comment]
The problem was the outdated version of Laravel-nuxt
