### ISSUE TITLE
Does vform 1.0.0 support file upload?

### ISSUE THREAD

**Issue by namdp06** [cretueusebiu/laravel-vue-spa#86]
I cannot do upload a file by post, put or patch with vform
but it work on vform 0.8.1
Request payload
`{"file":{}}`
instead of form-data

Content-type is: 
`Content-Type:application/json;charset=UTF-8`
instead of
`Content-Type:multipart/form-data;`

if there are another way to upload file. please teach me.
thank you.

**Comment by cretueusebiu** [comment]
The conversion to FormData was removed in [1.0.0](https://github.com/cretueusebiu/vform/releases/tag/1.0.0) because you can use axios `transformRequest` option. See the [upload example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).

**Comment by namdp06** [comment]
thank you very much for solving my problem.
