### ISSUE TITLE
Admin Section - Roles and Permissions

### ISSUE THREAD

**Issue by iamsrikanthgopi** [cretueusebiu/laravel-vue-spa#89]
I have completed a project using your template which helped me to finish easily.

The only thing im looking for now is a admin section to manage the site. Can i use spatie roles and permissions package with this template. Also i see admin.js in middleware. Is there a middleware already configured in this template? If yes, do i just need to create a role field in the users table? 

I do not want to mess up with my code so wanted to ask here before i begin?

**Comment by cretueusebiu** [comment]
This template does not provide an admin section, so you'll have to implement it. The admin middleware is there just as an example.
