### ISSUE TITLE
Ask about Kernel

### ISSUE THREAD

**Issue by lukashl** [cretueusebiu/laravel-vue-spa#9]
Hi, could you explain me, why deleted most web classes from Kernel? And, how you implement CSRF protection in app?

**Comment by cretueusebiu** [comment]
Because it uses just a JWT token so there's no need for sessions and cookies. You can just enable them back and add the csrf CSRF token via the [axios interceptor](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/util/interceptors.js).
