### ISSUE TITLE
Using google2fa package

### ISSUE THREAD

**Issue by ibrunotome** [cretueusebiu/laravel-vue-spa#90]
Hi, I use your template to learn how a SPA works. One of my questions when I was studying was "how would antonoribeiro / google2fa-laravel work in a SPA project, since it uses a laravel session to work with the timestamps?"

And I could not get an answer about that, so I got it by activating session middleware in the API middleware, but that's not good, since the API should be stateful.

Can you help with a solution to this case?

**Comment by cretueusebiu** [comment]
You'll have to remove the jwt token and just use session driver. Or see how you can use the cache for the g2fa secret instead of session.
