### ISSUE TITLE
url api server

### ISSUE THREAD

**Issue by mauro-gallo** [cretueusebiu/laravel-vue-spa#91]
How i can change the url of the api server?

**Comment by cretueusebiu** [comment]
The `/api` prefix or what ?

**Comment by mauro-gallo** [comment]
yes, i have an orrible english.
i want to use an external oauth2 server (alway a laravel passport server).

I see that there isn't a const prefix before the urls. Do you want that i create it?
Where do you prefer that i declare the consts?

**Comment by cretueusebiu** [comment]
Right now the prefix is hardcoded for each request. 
I guess you could just find and delete it and then use the axios interceptor to set the base url.
