### ISSUE TITLE
Implement Laravel Passport

### ISSUE THREAD

**Issue by mubbi** [cretueusebiu/laravel-vue-spa#92]
it will be good if you can remove the JWT and install Laravel passport as it provides full OAuth services for all parties of app.

**Comment by cretueusebiu** [comment]
I like to keep it simple. For jwt you don't have to store anything in the DB. Passport requires few tables.

**Comment by mubbi** [comment]
keeping simple is good but it's a boilerplate therefore I suggested adding passport as most of the applications will need that.

**Comment by Splean** [comment]
This application is just a starting point for more rapid development of what requires business from you. The whole "more complex" functionality you can implement yourself as a developer...
