### ISSUE TITLE
popup blocking for oauth logins

### ISSUE THREAD

**Issue by jrosczyk** [cretueusebiu/laravel-vue-spa#94]
Safari and Firefox are blocking the popup for Github login. After doing a quick search and test on it, looks like some browsers require the window.open to happen before using async.

**Comment by cretueusebiu** [comment]
Can you share that ?

**Comment by jrosczyk** [comment]
All I did was test it by adding `onClick="window.open('', null, 'width=600,height=720')"` to the Github button. And that opened an empty popup in Safari and Firefox. I didn't go any further. I guess I was thinking/hoping there was a fancy VueJS way to handle this, if not then I suppose I would open a new window first and then inside the async change the location.href of that window.

**Comment by jrosczyk** [comment]
Here is my work-around [solution](https://gist.github.com/jrosczyk/0edaeb1ba7787ce7086a63c211dbc223) for this. Feel free to use it or not.
